// Code generated by ent, DO NOT EDIT.

package stagebackendoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldLTE(FieldUpdatedAt, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v Stage) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v Stage) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...Stage) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...Stage) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNotIn(FieldStage, vs...))
}

// BackendModeEQ applies the EQ predicate on the "backend_mode" field.
func BackendModeEQ(v BackendMode) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldEQ(FieldBackendMode, v))
}

// BackendModeNEQ applies the NEQ predicate on the "backend_mode" field.
func BackendModeNEQ(v BackendMode) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNEQ(FieldBackendMode, v))
}

// BackendModeIn applies the In predicate on the "backend_mode" field.
func BackendModeIn(vs ...BackendMode) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldIn(FieldBackendMode, vs...))
}

// BackendModeNotIn applies the NotIn predicate on the "backend_mode" field.
func BackendModeNotIn(vs ...BackendMode) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.FieldNotIn(FieldBackendMode, vs...))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.StageBackendOverride {
	return predicate.StageBackendOverride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StageBackendOverride) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StageBackendOverride) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StageBackendOverride) predicate.StageBackendOverride {
	return predicate.StageBackendOverride(sql.NotPredicates(p))
}
