// Code generated by ent, DO NOT EDIT.

package storagemigrationitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldTaskID, v))
}

// BlobID applies equality check predicate on the "blob_id" field. It's identical to BlobIDEQ.
func BlobID(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldBlobID, v))
}

// SourceLocationID applies equality check predicate on the "source_location_id" field. It's identical to SourceLocationIDEQ.
func SourceLocationID(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldSourceLocationID, v))
}

// TargetLocationID applies equality check predicate on the "target_location_id" field. It's identical to TargetLocationIDEQ.
func TargetLocationID(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldTargetLocationID, v))
}

// ExpectedLocationGeneration applies equality check predicate on the "expected_location_generation" field. It's identical to ExpectedLocationGenerationEQ.
func ExpectedLocationGeneration(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldExpectedLocationGeneration, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldTaskID, vs...))
}

// BlobIDEQ applies the EQ predicate on the "blob_id" field.
func BlobIDEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldBlobID, v))
}

// BlobIDNEQ applies the NEQ predicate on the "blob_id" field.
func BlobIDNEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldBlobID, v))
}

// BlobIDIn applies the In predicate on the "blob_id" field.
func BlobIDIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldBlobID, vs...))
}

// BlobIDNotIn applies the NotIn predicate on the "blob_id" field.
func BlobIDNotIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldBlobID, vs...))
}

// SourceLocationIDEQ applies the EQ predicate on the "source_location_id" field.
func SourceLocationIDEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldSourceLocationID, v))
}

// SourceLocationIDNEQ applies the NEQ predicate on the "source_location_id" field.
func SourceLocationIDNEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldSourceLocationID, v))
}

// SourceLocationIDIn applies the In predicate on the "source_location_id" field.
func SourceLocationIDIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldSourceLocationID, vs...))
}

// SourceLocationIDNotIn applies the NotIn predicate on the "source_location_id" field.
func SourceLocationIDNotIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldSourceLocationID, vs...))
}

// TargetLocationIDEQ applies the EQ predicate on the "target_location_id" field.
func TargetLocationIDEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldTargetLocationID, v))
}

// TargetLocationIDNEQ applies the NEQ predicate on the "target_location_id" field.
func TargetLocationIDNEQ(v int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldTargetLocationID, v))
}

// TargetLocationIDIn applies the In predicate on the "target_location_id" field.
func TargetLocationIDIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldTargetLocationID, vs...))
}

// TargetLocationIDNotIn applies the NotIn predicate on the "target_location_id" field.
func TargetLocationIDNotIn(vs ...int) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldTargetLocationID, vs...))
}

// TargetLocationIDIsNil applies the IsNil predicate on the "target_location_id" field.
func TargetLocationIDIsNil() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIsNull(FieldTargetLocationID))
}

// TargetLocationIDNotNil applies the NotNil predicate on the "target_location_id" field.
func TargetLocationIDNotNil() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotNull(FieldTargetLocationID))
}

// ExpectedLocationGenerationEQ applies the EQ predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationEQ(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldExpectedLocationGeneration, v))
}

// ExpectedLocationGenerationNEQ applies the NEQ predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationNEQ(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldExpectedLocationGeneration, v))
}

// ExpectedLocationGenerationIn applies the In predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationIn(vs ...int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldExpectedLocationGeneration, vs...))
}

// ExpectedLocationGenerationNotIn applies the NotIn predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationNotIn(vs ...int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldExpectedLocationGeneration, vs...))
}

// ExpectedLocationGenerationGT applies the GT predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationGT(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGT(FieldExpectedLocationGeneration, v))
}

// ExpectedLocationGenerationGTE applies the GTE predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationGTE(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldGTE(FieldExpectedLocationGeneration, v))
}

// ExpectedLocationGenerationLT applies the LT predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationLT(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLT(FieldExpectedLocationGeneration, v))
}

// ExpectedLocationGenerationLTE applies the LTE predicate on the "expected_location_generation" field.
func ExpectedLocationGenerationLTE(v int64) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldLTE(FieldExpectedLocationGeneration, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.FieldNotIn(FieldStatus, vs...))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.StorageTask) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlob applies the HasEdge predicate on the "blob" edge.
func HasBlob() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, BlobTable, BlobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlobWith applies the HasEdge predicate on the "blob" edge with a given conditions (other predicates).
func HasBlobWith(preds ...predicate.Blob) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := newBlobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceLocation applies the HasEdge predicate on the "source_location" edge.
func HasSourceLocation() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SourceLocationTable, SourceLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceLocationWith applies the HasEdge predicate on the "source_location" edge with a given conditions (other predicates).
func HasSourceLocationWith(preds ...predicate.BlobLocation) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := newSourceLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetLocation applies the HasEdge predicate on the "target_location" edge.
func HasTargetLocation() predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TargetLocationTable, TargetLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetLocationWith applies the HasEdge predicate on the "target_location" edge with a given conditions (other predicates).
func HasTargetLocationWith(preds ...predicate.BlobLocation) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(func(s *sql.Selector) {
		step := newTargetLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StorageMigrationItem) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StorageMigrationItem) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StorageMigrationItem) predicate.StorageMigrationItem {
	return predicate.StorageMigrationItem(sql.NotPredicates(p))
}
