// Code generated by ent, DO NOT EDIT.

package sourcerevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldResourceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldProjectID, v))
}

// SourceBlobID applies equality check predicate on the "source_blob_id" field. It's identical to SourceBlobIDEQ.
func SourceBlobID(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSourceBlobID, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldFormat, v))
}

// ParserVersion applies equality check predicate on the "parser_version" field. It's identical to ParserVersionEQ.
func ParserVersion(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldParserVersion, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSize, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSha256, v))
}

// RetainUntil applies equality check predicate on the "retain_until" field. It's identical to RetainUntilEQ.
func RetainUntil(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldRetainUntil, v))
}

// Current applies equality check predicate on the "current" field. It's identical to CurrentEQ.
func Current(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldCurrent, v))
}

// Deleted applies equality check predicate on the "deleted" field. It's identical to DeletedEQ.
func Deleted(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldDeleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldUpdatedAt, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldResourceID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldProjectID, v))
}

// SourceBlobIDEQ applies the EQ predicate on the "source_blob_id" field.
func SourceBlobIDEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSourceBlobID, v))
}

// SourceBlobIDNEQ applies the NEQ predicate on the "source_blob_id" field.
func SourceBlobIDNEQ(v int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldSourceBlobID, v))
}

// SourceBlobIDIn applies the In predicate on the "source_blob_id" field.
func SourceBlobIDIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldSourceBlobID, vs...))
}

// SourceBlobIDNotIn applies the NotIn predicate on the "source_blob_id" field.
func SourceBlobIDNotIn(vs ...int) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldSourceBlobID, vs...))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContainsFold(FieldFormat, v))
}

// ParserVersionEQ applies the EQ predicate on the "parser_version" field.
func ParserVersionEQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldParserVersion, v))
}

// ParserVersionNEQ applies the NEQ predicate on the "parser_version" field.
func ParserVersionNEQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldParserVersion, v))
}

// ParserVersionIn applies the In predicate on the "parser_version" field.
func ParserVersionIn(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldParserVersion, vs...))
}

// ParserVersionNotIn applies the NotIn predicate on the "parser_version" field.
func ParserVersionNotIn(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldParserVersion, vs...))
}

// ParserVersionGT applies the GT predicate on the "parser_version" field.
func ParserVersionGT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldParserVersion, v))
}

// ParserVersionGTE applies the GTE predicate on the "parser_version" field.
func ParserVersionGTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldParserVersion, v))
}

// ParserVersionLT applies the LT predicate on the "parser_version" field.
func ParserVersionLT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldParserVersion, v))
}

// ParserVersionLTE applies the LTE predicate on the "parser_version" field.
func ParserVersionLTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldParserVersion, v))
}

// ParserVersionContains applies the Contains predicate on the "parser_version" field.
func ParserVersionContains(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContains(FieldParserVersion, v))
}

// ParserVersionHasPrefix applies the HasPrefix predicate on the "parser_version" field.
func ParserVersionHasPrefix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasPrefix(FieldParserVersion, v))
}

// ParserVersionHasSuffix applies the HasSuffix predicate on the "parser_version" field.
func ParserVersionHasSuffix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasSuffix(FieldParserVersion, v))
}

// ParserVersionEqualFold applies the EqualFold predicate on the "parser_version" field.
func ParserVersionEqualFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEqualFold(FieldParserVersion, v))
}

// ParserVersionContainsFold applies the ContainsFold predicate on the "parser_version" field.
func ParserVersionContainsFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContainsFold(FieldParserVersion, v))
}

// VerificationStateEQ applies the EQ predicate on the "verification_state" field.
func VerificationStateEQ(v VerificationState) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldVerificationState, v))
}

// VerificationStateNEQ applies the NEQ predicate on the "verification_state" field.
func VerificationStateNEQ(v VerificationState) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldVerificationState, v))
}

// VerificationStateIn applies the In predicate on the "verification_state" field.
func VerificationStateIn(vs ...VerificationState) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldVerificationState, vs...))
}

// VerificationStateNotIn applies the NotIn predicate on the "verification_state" field.
func VerificationStateNotIn(vs ...VerificationState) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldVerificationState, vs...))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotNull(FieldSize))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256IsNil applies the IsNil predicate on the "sha256" field.
func Sha256IsNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIsNull(FieldSha256))
}

// Sha256NotNil applies the NotNil predicate on the "sha256" field.
func Sha256NotNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotNull(FieldSha256))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldContainsFold(FieldSha256, v))
}

// RetainUntilEQ applies the EQ predicate on the "retain_until" field.
func RetainUntilEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldRetainUntil, v))
}

// RetainUntilNEQ applies the NEQ predicate on the "retain_until" field.
func RetainUntilNEQ(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldRetainUntil, v))
}

// RetainUntilIn applies the In predicate on the "retain_until" field.
func RetainUntilIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIn(FieldRetainUntil, vs...))
}

// RetainUntilNotIn applies the NotIn predicate on the "retain_until" field.
func RetainUntilNotIn(vs ...time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotIn(FieldRetainUntil, vs...))
}

// RetainUntilGT applies the GT predicate on the "retain_until" field.
func RetainUntilGT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGT(FieldRetainUntil, v))
}

// RetainUntilGTE applies the GTE predicate on the "retain_until" field.
func RetainUntilGTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldGTE(FieldRetainUntil, v))
}

// RetainUntilLT applies the LT predicate on the "retain_until" field.
func RetainUntilLT(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLT(FieldRetainUntil, v))
}

// RetainUntilLTE applies the LTE predicate on the "retain_until" field.
func RetainUntilLTE(v time.Time) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldLTE(FieldRetainUntil, v))
}

// RetainUntilIsNil applies the IsNil predicate on the "retain_until" field.
func RetainUntilIsNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldIsNull(FieldRetainUntil))
}

// RetainUntilNotNil applies the NotNil predicate on the "retain_until" field.
func RetainUntilNotNil() predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNotNull(FieldRetainUntil))
}

// CurrentEQ applies the EQ predicate on the "current" field.
func CurrentEQ(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldCurrent, v))
}

// CurrentNEQ applies the NEQ predicate on the "current" field.
func CurrentNEQ(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldCurrent, v))
}

// DeletedEQ applies the EQ predicate on the "deleted" field.
func DeletedEQ(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldEQ(FieldDeleted, v))
}

// DeletedNEQ applies the NEQ predicate on the "deleted" field.
func DeletedNEQ(v bool) predicate.SourceRevision {
	return predicate.SourceRevision(sql.FieldNEQ(FieldDeleted, v))
}

// HasBlob applies the HasEdge predicate on the "blob" edge.
func HasBlob() predicate.SourceRevision {
	return predicate.SourceRevision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, BlobTable, BlobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlobWith applies the HasEdge predicate on the "blob" edge with a given conditions (other predicates).
func HasBlobWith(preds ...predicate.Blob) predicate.SourceRevision {
	return predicate.SourceRevision(func(s *sql.Selector) {
		step := newBlobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceRevision) predicate.SourceRevision {
	return predicate.SourceRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceRevision) predicate.SourceRevision {
	return predicate.SourceRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceRevision) predicate.SourceRevision {
	return predicate.SourceRevision(sql.NotPredicates(p))
}
