// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProjectID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// TriggerType applies equality check predicate on the "trigger_type" field. It's identical to TriggerTypeEQ.
func TriggerType(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTriggerType, v))
}

// ExecutionPlanID applies equality check predicate on the "execution_plan_id" field. It's identical to ExecutionPlanIDEQ.
func ExecutionPlanID(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldExecutionPlanID, v))
}

// ResourceCount applies equality check predicate on the "resource_count" field. It's identical to ResourceCountEQ.
func ResourceCount(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldResourceCount, v))
}

// CompletedResources applies equality check predicate on the "completed_resources" field. It's identical to CompletedResourcesEQ.
func CompletedResources(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompletedResources, v))
}

// FailedResources applies equality check predicate on the "failed_resources" field. It's identical to FailedResourcesEQ.
func FailedResources(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFailedResources, v))
}

// TotalSegments applies equality check predicate on the "total_segments" field. It's identical to TotalSegmentsEQ.
func TotalSegments(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTotalSegments, v))
}

// SkippedSegments applies equality check predicate on the "skipped_segments" field. It's identical to SkippedSegmentsEQ.
func SkippedSegments(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSkippedSegments, v))
}

// StageTotal applies equality check predicate on the "stage_total" field. It's identical to StageTotalEQ.
func StageTotal(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStageTotal, v))
}

// CompletedSegments applies equality check predicate on the "completed_segments" field. It's identical to CompletedSegmentsEQ.
func CompletedSegments(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompletedSegments, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldProjectID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldStatus, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTriggerType, vs...))
}

// TriggerTypeGT applies the GT predicate on the "trigger_type" field.
func TriggerTypeGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldTriggerType, v))
}

// TriggerTypeGTE applies the GTE predicate on the "trigger_type" field.
func TriggerTypeGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldTriggerType, v))
}

// TriggerTypeLT applies the LT predicate on the "trigger_type" field.
func TriggerTypeLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldTriggerType, v))
}

// TriggerTypeLTE applies the LTE predicate on the "trigger_type" field.
func TriggerTypeLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldTriggerType, v))
}

// TriggerTypeContains applies the Contains predicate on the "trigger_type" field.
func TriggerTypeContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldTriggerType, v))
}

// TriggerTypeHasPrefix applies the HasPrefix predicate on the "trigger_type" field.
func TriggerTypeHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldTriggerType, v))
}

// TriggerTypeHasSuffix applies the HasSuffix predicate on the "trigger_type" field.
func TriggerTypeHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldTriggerType, v))
}

// TriggerTypeEqualFold applies the EqualFold predicate on the "trigger_type" field.
func TriggerTypeEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldTriggerType, v))
}

// TriggerTypeContainsFold applies the ContainsFold predicate on the "trigger_type" field.
func TriggerTypeContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldTriggerType, v))
}

// ExecutionPlanIDEQ applies the EQ predicate on the "execution_plan_id" field.
func ExecutionPlanIDEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldExecutionPlanID, v))
}

// ExecutionPlanIDNEQ applies the NEQ predicate on the "execution_plan_id" field.
func ExecutionPlanIDNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldExecutionPlanID, v))
}

// ExecutionPlanIDIn applies the In predicate on the "execution_plan_id" field.
func ExecutionPlanIDIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldExecutionPlanID, vs...))
}

// ExecutionPlanIDNotIn applies the NotIn predicate on the "execution_plan_id" field.
func ExecutionPlanIDNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldExecutionPlanID, vs...))
}

// ExecutionPlanIDGT applies the GT predicate on the "execution_plan_id" field.
func ExecutionPlanIDGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldExecutionPlanID, v))
}

// ExecutionPlanIDGTE applies the GTE predicate on the "execution_plan_id" field.
func ExecutionPlanIDGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldExecutionPlanID, v))
}

// ExecutionPlanIDLT applies the LT predicate on the "execution_plan_id" field.
func ExecutionPlanIDLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldExecutionPlanID, v))
}

// ExecutionPlanIDLTE applies the LTE predicate on the "execution_plan_id" field.
func ExecutionPlanIDLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldExecutionPlanID, v))
}

// ResourceCountEQ applies the EQ predicate on the "resource_count" field.
func ResourceCountEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldResourceCount, v))
}

// ResourceCountNEQ applies the NEQ predicate on the "resource_count" field.
func ResourceCountNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldResourceCount, v))
}

// ResourceCountIn applies the In predicate on the "resource_count" field.
func ResourceCountIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldResourceCount, vs...))
}

// ResourceCountNotIn applies the NotIn predicate on the "resource_count" field.
func ResourceCountNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldResourceCount, vs...))
}

// ResourceCountGT applies the GT predicate on the "resource_count" field.
func ResourceCountGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldResourceCount, v))
}

// ResourceCountGTE applies the GTE predicate on the "resource_count" field.
func ResourceCountGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldResourceCount, v))
}

// ResourceCountLT applies the LT predicate on the "resource_count" field.
func ResourceCountLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldResourceCount, v))
}

// ResourceCountLTE applies the LTE predicate on the "resource_count" field.
func ResourceCountLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldResourceCount, v))
}

// CompletedResourcesEQ applies the EQ predicate on the "completed_resources" field.
func CompletedResourcesEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompletedResources, v))
}

// CompletedResourcesNEQ applies the NEQ predicate on the "completed_resources" field.
func CompletedResourcesNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCompletedResources, v))
}

// CompletedResourcesIn applies the In predicate on the "completed_resources" field.
func CompletedResourcesIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCompletedResources, vs...))
}

// CompletedResourcesNotIn applies the NotIn predicate on the "completed_resources" field.
func CompletedResourcesNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCompletedResources, vs...))
}

// CompletedResourcesGT applies the GT predicate on the "completed_resources" field.
func CompletedResourcesGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCompletedResources, v))
}

// CompletedResourcesGTE applies the GTE predicate on the "completed_resources" field.
func CompletedResourcesGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCompletedResources, v))
}

// CompletedResourcesLT applies the LT predicate on the "completed_resources" field.
func CompletedResourcesLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCompletedResources, v))
}

// CompletedResourcesLTE applies the LTE predicate on the "completed_resources" field.
func CompletedResourcesLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCompletedResources, v))
}

// FailedResourcesEQ applies the EQ predicate on the "failed_resources" field.
func FailedResourcesEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFailedResources, v))
}

// FailedResourcesNEQ applies the NEQ predicate on the "failed_resources" field.
func FailedResourcesNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFailedResources, v))
}

// FailedResourcesIn applies the In predicate on the "failed_resources" field.
func FailedResourcesIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFailedResources, vs...))
}

// FailedResourcesNotIn applies the NotIn predicate on the "failed_resources" field.
func FailedResourcesNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFailedResources, vs...))
}

// FailedResourcesGT applies the GT predicate on the "failed_resources" field.
func FailedResourcesGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFailedResources, v))
}

// FailedResourcesGTE applies the GTE predicate on the "failed_resources" field.
func FailedResourcesGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFailedResources, v))
}

// FailedResourcesLT applies the LT predicate on the "failed_resources" field.
func FailedResourcesLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFailedResources, v))
}

// FailedResourcesLTE applies the LTE predicate on the "failed_resources" field.
func FailedResourcesLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFailedResources, v))
}

// TotalSegmentsEQ applies the EQ predicate on the "total_segments" field.
func TotalSegmentsEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTotalSegments, v))
}

// TotalSegmentsNEQ applies the NEQ predicate on the "total_segments" field.
func TotalSegmentsNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTotalSegments, v))
}

// TotalSegmentsIn applies the In predicate on the "total_segments" field.
func TotalSegmentsIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTotalSegments, vs...))
}

// TotalSegmentsNotIn applies the NotIn predicate on the "total_segments" field.
func TotalSegmentsNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTotalSegments, vs...))
}

// TotalSegmentsGT applies the GT predicate on the "total_segments" field.
func TotalSegmentsGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldTotalSegments, v))
}

// TotalSegmentsGTE applies the GTE predicate on the "total_segments" field.
func TotalSegmentsGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldTotalSegments, v))
}

// TotalSegmentsLT applies the LT predicate on the "total_segments" field.
func TotalSegmentsLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldTotalSegments, v))
}

// TotalSegmentsLTE applies the LTE predicate on the "total_segments" field.
func TotalSegmentsLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldTotalSegments, v))
}

// SkippedSegmentsEQ applies the EQ predicate on the "skipped_segments" field.
func SkippedSegmentsEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSkippedSegments, v))
}

// SkippedSegmentsNEQ applies the NEQ predicate on the "skipped_segments" field.
func SkippedSegmentsNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSkippedSegments, v))
}

// SkippedSegmentsIn applies the In predicate on the "skipped_segments" field.
func SkippedSegmentsIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSkippedSegments, vs...))
}

// SkippedSegmentsNotIn applies the NotIn predicate on the "skipped_segments" field.
func SkippedSegmentsNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSkippedSegments, vs...))
}

// SkippedSegmentsGT applies the GT predicate on the "skipped_segments" field.
func SkippedSegmentsGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSkippedSegments, v))
}

// SkippedSegmentsGTE applies the GTE predicate on the "skipped_segments" field.
func SkippedSegmentsGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSkippedSegments, v))
}

// SkippedSegmentsLT applies the LT predicate on the "skipped_segments" field.
func SkippedSegmentsLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSkippedSegments, v))
}

// SkippedSegmentsLTE applies the LTE predicate on the "skipped_segments" field.
func SkippedSegmentsLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSkippedSegments, v))
}

// StageTotalEQ applies the EQ predicate on the "stage_total" field.
func StageTotalEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStageTotal, v))
}

// StageTotalNEQ applies the NEQ predicate on the "stage_total" field.
func StageTotalNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStageTotal, v))
}

// StageTotalIn applies the In predicate on the "stage_total" field.
func StageTotalIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStageTotal, vs...))
}

// StageTotalNotIn applies the NotIn predicate on the "stage_total" field.
func StageTotalNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStageTotal, vs...))
}

// StageTotalGT applies the GT predicate on the "stage_total" field.
func StageTotalGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStageTotal, v))
}

// StageTotalGTE applies the GTE predicate on the "stage_total" field.
func StageTotalGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStageTotal, v))
}

// StageTotalLT applies the LT predicate on the "stage_total" field.
func StageTotalLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStageTotal, v))
}

// StageTotalLTE applies the LTE predicate on the "stage_total" field.
func StageTotalLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStageTotal, v))
}

// CompletedSegmentsEQ applies the EQ predicate on the "completed_segments" field.
func CompletedSegmentsEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompletedSegments, v))
}

// CompletedSegmentsNEQ applies the NEQ predicate on the "completed_segments" field.
func CompletedSegmentsNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCompletedSegments, v))
}

// CompletedSegmentsIn applies the In predicate on the "completed_segments" field.
func CompletedSegmentsIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCompletedSegments, vs...))
}

// CompletedSegmentsNotIn applies the NotIn predicate on the "completed_segments" field.
func CompletedSegmentsNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCompletedSegments, vs...))
}

// CompletedSegmentsGT applies the GT predicate on the "completed_segments" field.
func CompletedSegmentsGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCompletedSegments, v))
}

// CompletedSegmentsGTE applies the GTE predicate on the "completed_segments" field.
func CompletedSegmentsGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCompletedSegments, v))
}

// CompletedSegmentsLT applies the LT predicate on the "completed_segments" field.
func CompletedSegmentsLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCompletedSegments, v))
}

// CompletedSegmentsLTE applies the LTE predicate on the "completed_segments" field.
func CompletedSegmentsLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCompletedSegments, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldStartedAt))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJobResources applies the HasEdge predicate on the "job_resources" edge.
func HasJobResources() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, JobResourcesTable, JobResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobResourcesWith applies the HasEdge predicate on the "job_resources" edge with a given conditions (other predicates).
func HasJobResourcesWith(preds ...predicate.JobResource) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newJobResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSseEvents applies the HasEdge predicate on the "sse_events" edge.
func HasSseEvents() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SseEventsTable, SseEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSseEventsWith applies the HasEdge predicate on the "sse_events" edge with a given conditions (other predicates).
func HasSseEventsWith(preds ...predicate.SSEEvent) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newSseEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
