Project:
  type: object
  required: [id, name, source_lang, target_lang]
  properties:
    id:
      type: integer
    name:
      type: string
    owner_user_id:
      type: integer
    owner_org_id:
      type: integer
    config:
      type: object
      additionalProperties: true
    default_translation_config:
      type: object
      additionalProperties: true
    source_lang:
      type: string
    target_lang:
      type: string
    created_at:
      type: string
      format: date-time
    updated_at:
      type: string
      format: date-time

ProjectListResponse:
  type: object
  required: [items]
  properties:
    items:
      type: array
      items:
        $ref: '#/Project'

CreateProjectRequest:
  type: object
  required: [name]
  properties:
    name:
      type: string
    config:
      type: object
      additionalProperties: true
    default_translation_config:
      type: object
      additionalProperties: true
    source_lang:
      type: string
    target_lang:
      type: string
  additionalProperties: false

UpdateProjectRequest:
  type: object
  properties:
    name:
      type: string
    config:
      type: object
      additionalProperties: true
    default_translation_config:
      type: object
      additionalProperties: true
    source_lang:
      type: string
    target_lang:
      type: string
  additionalProperties: false

