// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/activitylog"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/organization"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/project"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/user"
)

// ActivityLogCreate is the builder for creating a ActivityLog entity.
type ActivityLogCreate struct {
	config
	mutation *ActivityLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityLogCreate) SetCreatedAt(v time.Time) *ActivityLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableCreatedAt(v *time.Time) *ActivityLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActivityLogCreate) SetUpdatedAt(v time.Time) *ActivityLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableUpdatedAt(v *time.Time) *ActivityLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *ActivityLogCreate) SetAction(v string) *ActivityLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *ActivityLogCreate) SetResourceType(v string) *ActivityLogCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ActivityLogCreate) SetResourceID(v int) *ActivityLogCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableResourceID(v *int) *ActivityLogCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ActivityLogCreate) SetMessage(v string) *ActivityLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableMessage(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ActivityLogCreate) SetMetadata(v map[string]interface{}) *ActivityLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_c *ActivityLogCreate) SetActorID(id int) *ActivityLogCreate {
	_c.mutation.SetActorID(id)
	return _c
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableActorID(id *int) *ActivityLogCreate {
	if id != nil {
		_c = _c.SetActorID(*id)
	}
	return _c
}

// SetActor sets the "actor" edge to the User entity.
func (_c *ActivityLogCreate) SetActor(v *User) *ActivityLogCreate {
	return _c.SetActorID(v.ID)
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *ActivityLogCreate) SetOrganizationID(id int) *ActivityLogCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetNillableOrganizationID sets the "organization" edge to the Organization entity by ID if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableOrganizationID(id *int) *ActivityLogCreate {
	if id != nil {
		_c = _c.SetOrganizationID(*id)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *ActivityLogCreate) SetOrganization(v *Organization) *ActivityLogCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ActivityLogCreate) SetProjectID(id int) *ActivityLogCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableProjectID(id *int) *ActivityLogCreate {
	if id != nil {
		_c = _c.SetProjectID(*id)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ActivityLogCreate) SetProject(v *Project) *ActivityLogCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (_c *ActivityLogCreate) Mutation() *ActivityLogMutation {
	return _c.mutation
}

// Save creates the ActivityLog in the database.
func (_c *ActivityLogCreate) Save(ctx context.Context) (*ActivityLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityLogCreate) SaveX(ctx context.Context) *ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activitylog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activitylog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := activitylog.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActivityLog.updated_at"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ActivityLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "ActivityLog.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := activitylog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := activitylog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "ActivityLog.metadata"`)}
	}
	return nil
}

func (_c *ActivityLogCreate) sqlSave(ctx context.Context) (*ActivityLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityLogCreate) createSpec() (*ActivityLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activitylog.Table, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activitylog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activitylog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(activitylog.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(activitylog.FieldResourceID, field.TypeInt, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(activitylog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(activitylog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.ActorTable,
			Columns: []string{activitylog.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_activity_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.OrganizationTable,
			Columns: []string{activitylog.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.organization_activity_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.ProjectTable,
			Columns: []string{activitylog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_activity_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivityLogCreateBulk is the builder for creating many ActivityLog entities in bulk.
type ActivityLogCreateBulk struct {
	config
	err      error
	builders []*ActivityLogCreate
}

// Save creates the ActivityLog entities in the database.
func (_c *ActivityLogCreateBulk) Save(ctx context.Context) ([]*ActivityLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivityLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) SaveX(ctx context.Context) []*ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
