// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/credentialjobreference"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/credentialversion"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// CredentialVersionUpdate is the builder for updating CredentialVersion entities.
type CredentialVersionUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialVersionMutation
}

// Where appends a list predicates to the CredentialVersionUpdate builder.
func (_u *CredentialVersionUpdate) Where(ps ...predicate.CredentialVersion) *CredentialVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialVersionUpdate) SetUpdatedAt(v time.Time) *CredentialVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEncryptionVersion sets the "encryption_version" field.
func (_u *CredentialVersionUpdate) SetEncryptionVersion(v int) *CredentialVersionUpdate {
	_u.mutation.ResetEncryptionVersion()
	_u.mutation.SetEncryptionVersion(v)
	return _u
}

// SetNillableEncryptionVersion sets the "encryption_version" field if the given value is not nil.
func (_u *CredentialVersionUpdate) SetNillableEncryptionVersion(v *int) *CredentialVersionUpdate {
	if v != nil {
		_u.SetEncryptionVersion(*v)
	}
	return _u
}

// AddEncryptionVersion adds value to the "encryption_version" field.
func (_u *CredentialVersionUpdate) AddEncryptionVersion(v int) *CredentialVersionUpdate {
	_u.mutation.AddEncryptionVersion(v)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *CredentialVersionUpdate) SetKeyID(v string) *CredentialVersionUpdate {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *CredentialVersionUpdate) SetNillableKeyID(v *string) *CredentialVersionUpdate {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *CredentialVersionUpdate) SetNonce(v []byte) *CredentialVersionUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *CredentialVersionUpdate) SetCiphertext(v []byte) *CredentialVersionUpdate {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *CredentialVersionUpdate) SetRevoked(v bool) *CredentialVersionUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *CredentialVersionUpdate) SetNillableRevoked(v *bool) *CredentialVersionUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// AddJobReferenceIDs adds the "job_references" edge to the CredentialJobReference entity by IDs.
func (_u *CredentialVersionUpdate) AddJobReferenceIDs(ids ...int) *CredentialVersionUpdate {
	_u.mutation.AddJobReferenceIDs(ids...)
	return _u
}

// AddJobReferences adds the "job_references" edges to the CredentialJobReference entity.
func (_u *CredentialVersionUpdate) AddJobReferences(v ...*CredentialJobReference) *CredentialVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobReferenceIDs(ids...)
}

// Mutation returns the CredentialVersionMutation object of the builder.
func (_u *CredentialVersionUpdate) Mutation() *CredentialVersionMutation {
	return _u.mutation
}

// ClearJobReferences clears all "job_references" edges to the CredentialJobReference entity.
func (_u *CredentialVersionUpdate) ClearJobReferences() *CredentialVersionUpdate {
	_u.mutation.ClearJobReferences()
	return _u
}

// RemoveJobReferenceIDs removes the "job_references" edge to CredentialJobReference entities by IDs.
func (_u *CredentialVersionUpdate) RemoveJobReferenceIDs(ids ...int) *CredentialVersionUpdate {
	_u.mutation.RemoveJobReferenceIDs(ids...)
	return _u
}

// RemoveJobReferences removes "job_references" edges to CredentialJobReference entities.
func (_u *CredentialVersionUpdate) RemoveJobReferences(v ...*CredentialJobReference) *CredentialVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobReferenceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialVersionUpdate) check() error {
	if v, ok := _u.mutation.EncryptionVersion(); ok {
		if err := credentialversion.EncryptionVersionValidator(v); err != nil {
			return &ValidationError{Name: "encryption_version", err: fmt.Errorf(`ent: validator failed for field "CredentialVersion.encryption_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyID(); ok {
		if err := credentialversion.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "CredentialVersion.key_id": %w`, err)}
		}
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CredentialVersion.credential"`)
	}
	return nil
}

func (_u *CredentialVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialversion.Table, credentialversion.Columns, sqlgraph.NewFieldSpec(credentialversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EncryptionVersion(); ok {
		_spec.SetField(credentialversion.FieldEncryptionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEncryptionVersion(); ok {
		_spec.AddField(credentialversion.FieldEncryptionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(credentialversion.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(credentialversion.FieldNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(credentialversion.FieldCiphertext, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(credentialversion.FieldRevoked, field.TypeBool, value)
	}
	if _u.mutation.JobReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobReferencesIDs(); len(nodes) > 0 && !_u.mutation.JobReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialVersionUpdateOne is the builder for updating a single CredentialVersion entity.
type CredentialVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialVersionUpdateOne) SetUpdatedAt(v time.Time) *CredentialVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEncryptionVersion sets the "encryption_version" field.
func (_u *CredentialVersionUpdateOne) SetEncryptionVersion(v int) *CredentialVersionUpdateOne {
	_u.mutation.ResetEncryptionVersion()
	_u.mutation.SetEncryptionVersion(v)
	return _u
}

// SetNillableEncryptionVersion sets the "encryption_version" field if the given value is not nil.
func (_u *CredentialVersionUpdateOne) SetNillableEncryptionVersion(v *int) *CredentialVersionUpdateOne {
	if v != nil {
		_u.SetEncryptionVersion(*v)
	}
	return _u
}

// AddEncryptionVersion adds value to the "encryption_version" field.
func (_u *CredentialVersionUpdateOne) AddEncryptionVersion(v int) *CredentialVersionUpdateOne {
	_u.mutation.AddEncryptionVersion(v)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *CredentialVersionUpdateOne) SetKeyID(v string) *CredentialVersionUpdateOne {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *CredentialVersionUpdateOne) SetNillableKeyID(v *string) *CredentialVersionUpdateOne {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *CredentialVersionUpdateOne) SetNonce(v []byte) *CredentialVersionUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *CredentialVersionUpdateOne) SetCiphertext(v []byte) *CredentialVersionUpdateOne {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *CredentialVersionUpdateOne) SetRevoked(v bool) *CredentialVersionUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *CredentialVersionUpdateOne) SetNillableRevoked(v *bool) *CredentialVersionUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// AddJobReferenceIDs adds the "job_references" edge to the CredentialJobReference entity by IDs.
func (_u *CredentialVersionUpdateOne) AddJobReferenceIDs(ids ...int) *CredentialVersionUpdateOne {
	_u.mutation.AddJobReferenceIDs(ids...)
	return _u
}

// AddJobReferences adds the "job_references" edges to the CredentialJobReference entity.
func (_u *CredentialVersionUpdateOne) AddJobReferences(v ...*CredentialJobReference) *CredentialVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobReferenceIDs(ids...)
}

// Mutation returns the CredentialVersionMutation object of the builder.
func (_u *CredentialVersionUpdateOne) Mutation() *CredentialVersionMutation {
	return _u.mutation
}

// ClearJobReferences clears all "job_references" edges to the CredentialJobReference entity.
func (_u *CredentialVersionUpdateOne) ClearJobReferences() *CredentialVersionUpdateOne {
	_u.mutation.ClearJobReferences()
	return _u
}

// RemoveJobReferenceIDs removes the "job_references" edge to CredentialJobReference entities by IDs.
func (_u *CredentialVersionUpdateOne) RemoveJobReferenceIDs(ids ...int) *CredentialVersionUpdateOne {
	_u.mutation.RemoveJobReferenceIDs(ids...)
	return _u
}

// RemoveJobReferences removes "job_references" edges to CredentialJobReference entities.
func (_u *CredentialVersionUpdateOne) RemoveJobReferences(v ...*CredentialJobReference) *CredentialVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobReferenceIDs(ids...)
}

// Where appends a list predicates to the CredentialVersionUpdate builder.
func (_u *CredentialVersionUpdateOne) Where(ps ...predicate.CredentialVersion) *CredentialVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialVersionUpdateOne) Select(field string, fields ...string) *CredentialVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CredentialVersion entity.
func (_u *CredentialVersionUpdateOne) Save(ctx context.Context) (*CredentialVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialVersionUpdateOne) SaveX(ctx context.Context) *CredentialVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CredentialVersionUpdateOne) check() error {
	if v, ok := _u.mutation.EncryptionVersion(); ok {
		if err := credentialversion.EncryptionVersionValidator(v); err != nil {
			return &ValidationError{Name: "encryption_version", err: fmt.Errorf(`ent: validator failed for field "CredentialVersion.encryption_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyID(); ok {
		if err := credentialversion.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "CredentialVersion.key_id": %w`, err)}
		}
	}
	if _u.mutation.CredentialCleared() && len(_u.mutation.CredentialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CredentialVersion.credential"`)
	}
	return nil
}

func (_u *CredentialVersionUpdateOne) sqlSave(ctx context.Context) (_node *CredentialVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credentialversion.Table, credentialversion.Columns, sqlgraph.NewFieldSpec(credentialversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CredentialVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentialversion.FieldID)
		for _, f := range fields {
			if !credentialversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentialversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EncryptionVersion(); ok {
		_spec.SetField(credentialversion.FieldEncryptionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEncryptionVersion(); ok {
		_spec.AddField(credentialversion.FieldEncryptionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(credentialversion.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(credentialversion.FieldNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(credentialversion.FieldCiphertext, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(credentialversion.FieldRevoked, field.TypeBool, value)
	}
	if _u.mutation.JobReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobReferencesIDs(); len(nodes) > 0 && !_u.mutation.JobReferencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobReferencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   credentialversion.JobReferencesTable,
			Columns: []string{credentialversion.JobReferencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credentialjobreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CredentialVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
