// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/job"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobresource"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobround"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// JobRoundQuery is the builder for querying JobRound entities.
type JobRoundQuery struct {
	config
	ctx             *QueryContext
	order           []jobround.OrderOption
	inters          []Interceptor
	predicates      []predicate.JobRound
	withJob         *JobQuery
	withJobResource *JobResourceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobRoundQuery builder.
func (_q *JobRoundQuery) Where(ps ...predicate.JobRound) *JobRoundQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *JobRoundQuery) Limit(limit int) *JobRoundQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *JobRoundQuery) Offset(offset int) *JobRoundQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *JobRoundQuery) Unique(unique bool) *JobRoundQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *JobRoundQuery) Order(o ...jobround.OrderOption) *JobRoundQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryJob chains the current query on the "job" edge.
func (_q *JobRoundQuery) QueryJob() *JobQuery {
	query := (&JobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobround.Table, jobround.FieldID, selector),
			sqlgraph.To(job.Table, job.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobround.JobTable, jobround.JobColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobResource chains the current query on the "job_resource" edge.
func (_q *JobRoundQuery) QueryJobResource() *JobResourceQuery {
	query := (&JobResourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobround.Table, jobround.FieldID, selector),
			sqlgraph.To(jobresource.Table, jobresource.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobround.JobResourceTable, jobround.JobResourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JobRound entity from the query.
// Returns a *NotFoundError when no JobRound was found.
func (_q *JobRoundQuery) First(ctx context.Context) (*JobRound, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobround.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *JobRoundQuery) FirstX(ctx context.Context) *JobRound {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobRound ID from the query.
// Returns a *NotFoundError when no JobRound ID was found.
func (_q *JobRoundQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobround.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *JobRoundQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobRound entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobRound entity is found.
// Returns a *NotFoundError when no JobRound entities are found.
func (_q *JobRoundQuery) Only(ctx context.Context) (*JobRound, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobround.Label}
	default:
		return nil, &NotSingularError{jobround.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *JobRoundQuery) OnlyX(ctx context.Context) *JobRound {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobRound ID in the query.
// Returns a *NotSingularError when more than one JobRound ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *JobRoundQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobround.Label}
	default:
		err = &NotSingularError{jobround.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *JobRoundQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobRounds.
func (_q *JobRoundQuery) All(ctx context.Context) ([]*JobRound, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobRound, *JobRoundQuery]()
	return withInterceptors[[]*JobRound](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *JobRoundQuery) AllX(ctx context.Context) []*JobRound {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobRound IDs.
func (_q *JobRoundQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(jobround.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *JobRoundQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *JobRoundQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*JobRoundQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *JobRoundQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *JobRoundQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *JobRoundQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobRoundQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *JobRoundQuery) Clone() *JobRoundQuery {
	if _q == nil {
		return nil
	}
	return &JobRoundQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]jobround.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.JobRound{}, _q.predicates...),
		withJob:         _q.withJob.Clone(),
		withJobResource: _q.withJobResource.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithJob tells the query-builder to eager-load the nodes that are connected to
// the "job" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *JobRoundQuery) WithJob(opts ...func(*JobQuery)) *JobRoundQuery {
	query := (&JobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withJob = query
	return _q
}

// WithJobResource tells the query-builder to eager-load the nodes that are connected to
// the "job_resource" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *JobRoundQuery) WithJobResource(opts ...func(*JobResourceQuery)) *JobRoundQuery {
	query := (&JobResourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withJobResource = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobRound.Query().
//		GroupBy(jobround.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *JobRoundQuery) GroupBy(field string, fields ...string) *JobRoundGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobRoundGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = jobround.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.JobRound.Query().
//		Select(jobround.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *JobRoundQuery) Select(fields ...string) *JobRoundSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &JobRoundSelect{JobRoundQuery: _q}
	sbuild.label = jobround.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobRoundSelect configured with the given aggregations.
func (_q *JobRoundQuery) Aggregate(fns ...AggregateFunc) *JobRoundSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *JobRoundQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !jobround.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *JobRoundQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobRound, error) {
	var (
		nodes       = []*JobRound{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withJob != nil,
			_q.withJobResource != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobRound).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobRound{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withJob; query != nil {
		if err := _q.loadJob(ctx, query, nodes, nil,
			func(n *JobRound, e *Job) { n.Edges.Job = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withJobResource; query != nil {
		if err := _q.loadJobResource(ctx, query, nodes, nil,
			func(n *JobRound, e *JobResource) { n.Edges.JobResource = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *JobRoundQuery) loadJob(ctx context.Context, query *JobQuery, nodes []*JobRound, init func(*JobRound), assign func(*JobRound, *Job)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*JobRound)
	for i := range nodes {
		fk := nodes[i].JobID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(job.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "job_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *JobRoundQuery) loadJobResource(ctx context.Context, query *JobResourceQuery, nodes []*JobRound, init func(*JobRound), assign func(*JobRound, *JobResource)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*JobRound)
	for i := range nodes {
		fk := nodes[i].JobResourceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(jobresource.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "job_resource_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *JobRoundQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *JobRoundQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobround.Table, jobround.Columns, sqlgraph.NewFieldSpec(jobround.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobround.FieldID)
		for i := range fields {
			if fields[i] != jobround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withJob != nil {
			_spec.Node.AddColumnOnce(jobround.FieldJobID)
		}
		if _q.withJobResource != nil {
			_spec.Node.AddColumnOnce(jobround.FieldJobResourceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *JobRoundQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(jobround.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = jobround.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobRoundGroupBy is the group-by builder for JobRound entities.
type JobRoundGroupBy struct {
	selector
	build *JobRoundQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *JobRoundGroupBy) Aggregate(fns ...AggregateFunc) *JobRoundGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *JobRoundGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobRoundQuery, *JobRoundGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *JobRoundGroupBy) sqlScan(ctx context.Context, root *JobRoundQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobRoundSelect is the builder for selecting fields of JobRound entities.
type JobRoundSelect struct {
	*JobRoundQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *JobRoundSelect) Aggregate(fns ...AggregateFunc) *JobRoundSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *JobRoundSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobRoundQuery, *JobRoundSelect](ctx, _s.JobRoundQuery, _s, _s.inters, v)
}

func (_s *JobRoundSelect) sqlScan(ctx context.Context, root *JobRoundQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
