// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/job"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobresource"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobround"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobroundsegment"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/segment"
)

// JobRoundUpdate is the builder for updating JobRound entities.
type JobRoundUpdate struct {
	config
	hooks    []Hook
	mutation *JobRoundMutation
}

// Where appends a list predicates to the JobRoundUpdate builder.
func (_u *JobRoundUpdate) Where(ps ...predicate.JobRound) *JobRoundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobRoundUpdate) SetUpdatedAt(v time.Time) *JobRoundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *JobRoundUpdate) SetJobID(v int) *JobRoundUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableJobID(v *int) *JobRoundUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetJobResourceID sets the "job_resource_id" field.
func (_u *JobRoundUpdate) SetJobResourceID(v int) *JobRoundUpdate {
	_u.mutation.SetJobResourceID(v)
	return _u
}

// SetNillableJobResourceID sets the "job_resource_id" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableJobResourceID(v *int) *JobRoundUpdate {
	if v != nil {
		_u.SetJobResourceID(*v)
	}
	return _u
}

// SetRoundIndex sets the "round_index" field.
func (_u *JobRoundUpdate) SetRoundIndex(v int) *JobRoundUpdate {
	_u.mutation.ResetRoundIndex()
	_u.mutation.SetRoundIndex(v)
	return _u
}

// SetNillableRoundIndex sets the "round_index" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableRoundIndex(v *int) *JobRoundUpdate {
	if v != nil {
		_u.SetRoundIndex(*v)
	}
	return _u
}

// AddRoundIndex adds value to the "round_index" field.
func (_u *JobRoundUpdate) AddRoundIndex(v int) *JobRoundUpdate {
	_u.mutation.AddRoundIndex(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *JobRoundUpdate) SetMode(v string) *JobRoundUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableMode(v *string) *JobRoundUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobRoundUpdate) SetStatus(v string) *JobRoundUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableStatus(v *string) *JobRoundUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSegmentTotal sets the "segment_total" field.
func (_u *JobRoundUpdate) SetSegmentTotal(v int) *JobRoundUpdate {
	_u.mutation.ResetSegmentTotal()
	_u.mutation.SetSegmentTotal(v)
	return _u
}

// SetNillableSegmentTotal sets the "segment_total" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableSegmentTotal(v *int) *JobRoundUpdate {
	if v != nil {
		_u.SetSegmentTotal(*v)
	}
	return _u
}

// AddSegmentTotal adds value to the "segment_total" field.
func (_u *JobRoundUpdate) AddSegmentTotal(v int) *JobRoundUpdate {
	_u.mutation.AddSegmentTotal(v)
	return _u
}

// SetSegmentCompleted sets the "segment_completed" field.
func (_u *JobRoundUpdate) SetSegmentCompleted(v int) *JobRoundUpdate {
	_u.mutation.ResetSegmentCompleted()
	_u.mutation.SetSegmentCompleted(v)
	return _u
}

// SetNillableSegmentCompleted sets the "segment_completed" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableSegmentCompleted(v *int) *JobRoundUpdate {
	if v != nil {
		_u.SetSegmentCompleted(*v)
	}
	return _u
}

// AddSegmentCompleted adds value to the "segment_completed" field.
func (_u *JobRoundUpdate) AddSegmentCompleted(v int) *JobRoundUpdate {
	_u.mutation.AddSegmentCompleted(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *JobRoundUpdate) SetErrorMessage(v string) *JobRoundUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableErrorMessage(v *string) *JobRoundUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *JobRoundUpdate) ClearErrorMessage() *JobRoundUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobRoundUpdate) SetStartedAt(v time.Time) *JobRoundUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableStartedAt(v *time.Time) *JobRoundUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobRoundUpdate) ClearStartedAt() *JobRoundUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobRoundUpdate) SetFinishedAt(v time.Time) *JobRoundUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobRoundUpdate) SetNillableFinishedAt(v *time.Time) *JobRoundUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobRoundUpdate) ClearFinishedAt() *JobRoundUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetJob sets the "job" edge to the Job entity.
func (_u *JobRoundUpdate) SetJob(v *Job) *JobRoundUpdate {
	return _u.SetJobID(v.ID)
}

// SetJobResource sets the "job_resource" edge to the JobResource entity.
func (_u *JobRoundUpdate) SetJobResource(v *JobResource) *JobRoundUpdate {
	return _u.SetJobResourceID(v.ID)
}

// AddResolvedSegmentIDs adds the "resolved_segments" edge to the Segment entity by IDs.
func (_u *JobRoundUpdate) AddResolvedSegmentIDs(ids ...int) *JobRoundUpdate {
	_u.mutation.AddResolvedSegmentIDs(ids...)
	return _u
}

// AddResolvedSegments adds the "resolved_segments" edges to the Segment entity.
func (_u *JobRoundUpdate) AddResolvedSegments(v ...*Segment) *JobRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResolvedSegmentIDs(ids...)
}

// AddJobRoundSegmentIDs adds the "job_round_segments" edge to the JobRoundSegment entity by IDs.
func (_u *JobRoundUpdate) AddJobRoundSegmentIDs(ids ...int) *JobRoundUpdate {
	_u.mutation.AddJobRoundSegmentIDs(ids...)
	return _u
}

// AddJobRoundSegments adds the "job_round_segments" edges to the JobRoundSegment entity.
func (_u *JobRoundUpdate) AddJobRoundSegments(v ...*JobRoundSegment) *JobRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobRoundSegmentIDs(ids...)
}

// Mutation returns the JobRoundMutation object of the builder.
func (_u *JobRoundUpdate) Mutation() *JobRoundMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the Job entity.
func (_u *JobRoundUpdate) ClearJob() *JobRoundUpdate {
	_u.mutation.ClearJob()
	return _u
}

// ClearJobResource clears the "job_resource" edge to the JobResource entity.
func (_u *JobRoundUpdate) ClearJobResource() *JobRoundUpdate {
	_u.mutation.ClearJobResource()
	return _u
}

// ClearResolvedSegments clears all "resolved_segments" edges to the Segment entity.
func (_u *JobRoundUpdate) ClearResolvedSegments() *JobRoundUpdate {
	_u.mutation.ClearResolvedSegments()
	return _u
}

// RemoveResolvedSegmentIDs removes the "resolved_segments" edge to Segment entities by IDs.
func (_u *JobRoundUpdate) RemoveResolvedSegmentIDs(ids ...int) *JobRoundUpdate {
	_u.mutation.RemoveResolvedSegmentIDs(ids...)
	return _u
}

// RemoveResolvedSegments removes "resolved_segments" edges to Segment entities.
func (_u *JobRoundUpdate) RemoveResolvedSegments(v ...*Segment) *JobRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResolvedSegmentIDs(ids...)
}

// ClearJobRoundSegments clears all "job_round_segments" edges to the JobRoundSegment entity.
func (_u *JobRoundUpdate) ClearJobRoundSegments() *JobRoundUpdate {
	_u.mutation.ClearJobRoundSegments()
	return _u
}

// RemoveJobRoundSegmentIDs removes the "job_round_segments" edge to JobRoundSegment entities by IDs.
func (_u *JobRoundUpdate) RemoveJobRoundSegmentIDs(ids ...int) *JobRoundUpdate {
	_u.mutation.RemoveJobRoundSegmentIDs(ids...)
	return _u
}

// RemoveJobRoundSegments removes "job_round_segments" edges to JobRoundSegment entities.
func (_u *JobRoundUpdate) RemoveJobRoundSegments(v ...*JobRoundSegment) *JobRoundUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobRoundSegmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobRoundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobRoundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobRoundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobRoundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobRoundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := jobround.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobRoundUpdate) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := jobround.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "JobRound.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobResourceID(); ok {
		if err := jobround.JobResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "job_resource_id", err: fmt.Errorf(`ent: validator failed for field "JobRound.job_resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoundIndex(); ok {
		if err := jobround.RoundIndexValidator(v); err != nil {
			return &ValidationError{Name: "round_index", err: fmt.Errorf(`ent: validator failed for field "JobRound.round_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentTotal(); ok {
		if err := jobround.SegmentTotalValidator(v); err != nil {
			return &ValidationError{Name: "segment_total", err: fmt.Errorf(`ent: validator failed for field "JobRound.segment_total": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentCompleted(); ok {
		if err := jobround.SegmentCompletedValidator(v); err != nil {
			return &ValidationError{Name: "segment_completed", err: fmt.Errorf(`ent: validator failed for field "JobRound.segment_completed": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobRound.job"`)
	}
	if _u.mutation.JobResourceCleared() && len(_u.mutation.JobResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobRound.job_resource"`)
	}
	return nil
}

func (_u *JobRoundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobround.Table, jobround.Columns, sqlgraph.NewFieldSpec(jobround.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(jobround.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoundIndex(); ok {
		_spec.SetField(jobround.FieldRoundIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundIndex(); ok {
		_spec.AddField(jobround.FieldRoundIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(jobround.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(jobround.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentTotal(); ok {
		_spec.SetField(jobround.FieldSegmentTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSegmentTotal(); ok {
		_spec.AddField(jobround.FieldSegmentTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SegmentCompleted(); ok {
		_spec.SetField(jobround.FieldSegmentCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSegmentCompleted(); ok {
		_spec.AddField(jobround.FieldSegmentCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(jobround.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(jobround.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(jobround.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(jobround.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(jobround.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(jobround.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobTable,
			Columns: []string{jobround.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobTable,
			Columns: []string{jobround.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobResourceTable,
			Columns: []string{jobround.JobResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobresource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobResourceTable,
			Columns: []string{jobround.JobResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResolvedSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResolvedSegmentsIDs(); len(nodes) > 0 && !_u.mutation.ResolvedSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResolvedSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobRoundSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobRoundSegmentsIDs(); len(nodes) > 0 && !_u.mutation.JobRoundSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobRoundSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobround.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobRoundUpdateOne is the builder for updating a single JobRound entity.
type JobRoundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobRoundMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JobRoundUpdateOne) SetUpdatedAt(v time.Time) *JobRoundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *JobRoundUpdateOne) SetJobID(v int) *JobRoundUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableJobID(v *int) *JobRoundUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetJobResourceID sets the "job_resource_id" field.
func (_u *JobRoundUpdateOne) SetJobResourceID(v int) *JobRoundUpdateOne {
	_u.mutation.SetJobResourceID(v)
	return _u
}

// SetNillableJobResourceID sets the "job_resource_id" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableJobResourceID(v *int) *JobRoundUpdateOne {
	if v != nil {
		_u.SetJobResourceID(*v)
	}
	return _u
}

// SetRoundIndex sets the "round_index" field.
func (_u *JobRoundUpdateOne) SetRoundIndex(v int) *JobRoundUpdateOne {
	_u.mutation.ResetRoundIndex()
	_u.mutation.SetRoundIndex(v)
	return _u
}

// SetNillableRoundIndex sets the "round_index" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableRoundIndex(v *int) *JobRoundUpdateOne {
	if v != nil {
		_u.SetRoundIndex(*v)
	}
	return _u
}

// AddRoundIndex adds value to the "round_index" field.
func (_u *JobRoundUpdateOne) AddRoundIndex(v int) *JobRoundUpdateOne {
	_u.mutation.AddRoundIndex(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *JobRoundUpdateOne) SetMode(v string) *JobRoundUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableMode(v *string) *JobRoundUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobRoundUpdateOne) SetStatus(v string) *JobRoundUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableStatus(v *string) *JobRoundUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSegmentTotal sets the "segment_total" field.
func (_u *JobRoundUpdateOne) SetSegmentTotal(v int) *JobRoundUpdateOne {
	_u.mutation.ResetSegmentTotal()
	_u.mutation.SetSegmentTotal(v)
	return _u
}

// SetNillableSegmentTotal sets the "segment_total" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableSegmentTotal(v *int) *JobRoundUpdateOne {
	if v != nil {
		_u.SetSegmentTotal(*v)
	}
	return _u
}

// AddSegmentTotal adds value to the "segment_total" field.
func (_u *JobRoundUpdateOne) AddSegmentTotal(v int) *JobRoundUpdateOne {
	_u.mutation.AddSegmentTotal(v)
	return _u
}

// SetSegmentCompleted sets the "segment_completed" field.
func (_u *JobRoundUpdateOne) SetSegmentCompleted(v int) *JobRoundUpdateOne {
	_u.mutation.ResetSegmentCompleted()
	_u.mutation.SetSegmentCompleted(v)
	return _u
}

// SetNillableSegmentCompleted sets the "segment_completed" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableSegmentCompleted(v *int) *JobRoundUpdateOne {
	if v != nil {
		_u.SetSegmentCompleted(*v)
	}
	return _u
}

// AddSegmentCompleted adds value to the "segment_completed" field.
func (_u *JobRoundUpdateOne) AddSegmentCompleted(v int) *JobRoundUpdateOne {
	_u.mutation.AddSegmentCompleted(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *JobRoundUpdateOne) SetErrorMessage(v string) *JobRoundUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableErrorMessage(v *string) *JobRoundUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *JobRoundUpdateOne) ClearErrorMessage() *JobRoundUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *JobRoundUpdateOne) SetStartedAt(v time.Time) *JobRoundUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableStartedAt(v *time.Time) *JobRoundUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *JobRoundUpdateOne) ClearStartedAt() *JobRoundUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobRoundUpdateOne) SetFinishedAt(v time.Time) *JobRoundUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobRoundUpdateOne) SetNillableFinishedAt(v *time.Time) *JobRoundUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobRoundUpdateOne) ClearFinishedAt() *JobRoundUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetJob sets the "job" edge to the Job entity.
func (_u *JobRoundUpdateOne) SetJob(v *Job) *JobRoundUpdateOne {
	return _u.SetJobID(v.ID)
}

// SetJobResource sets the "job_resource" edge to the JobResource entity.
func (_u *JobRoundUpdateOne) SetJobResource(v *JobResource) *JobRoundUpdateOne {
	return _u.SetJobResourceID(v.ID)
}

// AddResolvedSegmentIDs adds the "resolved_segments" edge to the Segment entity by IDs.
func (_u *JobRoundUpdateOne) AddResolvedSegmentIDs(ids ...int) *JobRoundUpdateOne {
	_u.mutation.AddResolvedSegmentIDs(ids...)
	return _u
}

// AddResolvedSegments adds the "resolved_segments" edges to the Segment entity.
func (_u *JobRoundUpdateOne) AddResolvedSegments(v ...*Segment) *JobRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResolvedSegmentIDs(ids...)
}

// AddJobRoundSegmentIDs adds the "job_round_segments" edge to the JobRoundSegment entity by IDs.
func (_u *JobRoundUpdateOne) AddJobRoundSegmentIDs(ids ...int) *JobRoundUpdateOne {
	_u.mutation.AddJobRoundSegmentIDs(ids...)
	return _u
}

// AddJobRoundSegments adds the "job_round_segments" edges to the JobRoundSegment entity.
func (_u *JobRoundUpdateOne) AddJobRoundSegments(v ...*JobRoundSegment) *JobRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobRoundSegmentIDs(ids...)
}

// Mutation returns the JobRoundMutation object of the builder.
func (_u *JobRoundUpdateOne) Mutation() *JobRoundMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the Job entity.
func (_u *JobRoundUpdateOne) ClearJob() *JobRoundUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// ClearJobResource clears the "job_resource" edge to the JobResource entity.
func (_u *JobRoundUpdateOne) ClearJobResource() *JobRoundUpdateOne {
	_u.mutation.ClearJobResource()
	return _u
}

// ClearResolvedSegments clears all "resolved_segments" edges to the Segment entity.
func (_u *JobRoundUpdateOne) ClearResolvedSegments() *JobRoundUpdateOne {
	_u.mutation.ClearResolvedSegments()
	return _u
}

// RemoveResolvedSegmentIDs removes the "resolved_segments" edge to Segment entities by IDs.
func (_u *JobRoundUpdateOne) RemoveResolvedSegmentIDs(ids ...int) *JobRoundUpdateOne {
	_u.mutation.RemoveResolvedSegmentIDs(ids...)
	return _u
}

// RemoveResolvedSegments removes "resolved_segments" edges to Segment entities.
func (_u *JobRoundUpdateOne) RemoveResolvedSegments(v ...*Segment) *JobRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResolvedSegmentIDs(ids...)
}

// ClearJobRoundSegments clears all "job_round_segments" edges to the JobRoundSegment entity.
func (_u *JobRoundUpdateOne) ClearJobRoundSegments() *JobRoundUpdateOne {
	_u.mutation.ClearJobRoundSegments()
	return _u
}

// RemoveJobRoundSegmentIDs removes the "job_round_segments" edge to JobRoundSegment entities by IDs.
func (_u *JobRoundUpdateOne) RemoveJobRoundSegmentIDs(ids ...int) *JobRoundUpdateOne {
	_u.mutation.RemoveJobRoundSegmentIDs(ids...)
	return _u
}

// RemoveJobRoundSegments removes "job_round_segments" edges to JobRoundSegment entities.
func (_u *JobRoundUpdateOne) RemoveJobRoundSegments(v ...*JobRoundSegment) *JobRoundUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobRoundSegmentIDs(ids...)
}

// Where appends a list predicates to the JobRoundUpdate builder.
func (_u *JobRoundUpdateOne) Where(ps ...predicate.JobRound) *JobRoundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobRoundUpdateOne) Select(field string, fields ...string) *JobRoundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JobRound entity.
func (_u *JobRoundUpdateOne) Save(ctx context.Context) (*JobRound, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobRoundUpdateOne) SaveX(ctx context.Context) *JobRound {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobRoundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobRoundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JobRoundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := jobround.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobRoundUpdateOne) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := jobround.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "JobRound.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobResourceID(); ok {
		if err := jobround.JobResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "job_resource_id", err: fmt.Errorf(`ent: validator failed for field "JobRound.job_resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoundIndex(); ok {
		if err := jobround.RoundIndexValidator(v); err != nil {
			return &ValidationError{Name: "round_index", err: fmt.Errorf(`ent: validator failed for field "JobRound.round_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentTotal(); ok {
		if err := jobround.SegmentTotalValidator(v); err != nil {
			return &ValidationError{Name: "segment_total", err: fmt.Errorf(`ent: validator failed for field "JobRound.segment_total": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SegmentCompleted(); ok {
		if err := jobround.SegmentCompletedValidator(v); err != nil {
			return &ValidationError{Name: "segment_completed", err: fmt.Errorf(`ent: validator failed for field "JobRound.segment_completed": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobRound.job"`)
	}
	if _u.mutation.JobResourceCleared() && len(_u.mutation.JobResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobRound.job_resource"`)
	}
	return nil
}

func (_u *JobRoundUpdateOne) sqlSave(ctx context.Context) (_node *JobRound, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobround.Table, jobround.Columns, sqlgraph.NewFieldSpec(jobround.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobRound.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobround.FieldID)
		for _, f := range fields {
			if !jobround.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(jobround.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoundIndex(); ok {
		_spec.SetField(jobround.FieldRoundIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoundIndex(); ok {
		_spec.AddField(jobround.FieldRoundIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(jobround.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(jobround.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SegmentTotal(); ok {
		_spec.SetField(jobround.FieldSegmentTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSegmentTotal(); ok {
		_spec.AddField(jobround.FieldSegmentTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SegmentCompleted(); ok {
		_spec.SetField(jobround.FieldSegmentCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSegmentCompleted(); ok {
		_spec.AddField(jobround.FieldSegmentCompleted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(jobround.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(jobround.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(jobround.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(jobround.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(jobround.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(jobround.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobTable,
			Columns: []string{jobround.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobTable,
			Columns: []string{jobround.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobResourceTable,
			Columns: []string{jobround.JobResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobresource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   jobround.JobResourceTable,
			Columns: []string{jobround.JobResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResolvedSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResolvedSegmentsIDs(); len(nodes) > 0 && !_u.mutation.ResolvedSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResolvedSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   jobround.ResolvedSegmentsTable,
			Columns: jobround.ResolvedSegmentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JobRoundSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobRoundSegmentsIDs(); len(nodes) > 0 && !_u.mutation.JobRoundSegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobRoundSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   jobround.JobRoundSegmentsTable,
			Columns: []string{jobround.JobRoundSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(jobroundsegment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &JobRound{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobround.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
