// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/activitylog"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/backend"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/bootstrapprompttemplate"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/executionplantemplate"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/glossaryentry"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/job"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/jobresource"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/organization"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/orgmembership"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/project"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/refreshtoken"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/resource"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/schema"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/segment"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/sseevent"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/synctask"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/systemsetting"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/tmentry"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/translationprofile"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/translationprompttemplate"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/usagerecord"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activitylogMixin := schema.ActivityLog{}.Mixin()
	activitylogMixinFields0 := activitylogMixin[0].Fields()
	_ = activitylogMixinFields0
	activitylogFields := schema.ActivityLog{}.Fields()
	_ = activitylogFields
	// activitylogDescCreatedAt is the schema descriptor for created_at field.
	activitylogDescCreatedAt := activitylogMixinFields0[0].Descriptor()
	// activitylog.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitylog.DefaultCreatedAt = activitylogDescCreatedAt.Default.(func() time.Time)
	// activitylogDescUpdatedAt is the schema descriptor for updated_at field.
	activitylogDescUpdatedAt := activitylogMixinFields0[1].Descriptor()
	// activitylog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	activitylog.DefaultUpdatedAt = activitylogDescUpdatedAt.Default.(func() time.Time)
	// activitylog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	activitylog.UpdateDefaultUpdatedAt = activitylogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// activitylogDescAction is the schema descriptor for action field.
	activitylogDescAction := activitylogFields[0].Descriptor()
	// activitylog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	activitylog.ActionValidator = activitylogDescAction.Validators[0].(func(string) error)
	// activitylogDescResourceType is the schema descriptor for resource_type field.
	activitylogDescResourceType := activitylogFields[1].Descriptor()
	// activitylog.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	activitylog.ResourceTypeValidator = activitylogDescResourceType.Validators[0].(func(string) error)
	// activitylogDescResourceID is the schema descriptor for resource_id field.
	activitylogDescResourceID := activitylogFields[2].Descriptor()
	// activitylog.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	activitylog.ResourceIDValidator = activitylogDescResourceID.Validators[0].(func(int) error)
	// activitylogDescMetadata is the schema descriptor for metadata field.
	activitylogDescMetadata := activitylogFields[4].Descriptor()
	// activitylog.DefaultMetadata holds the default value on creation for the metadata field.
	activitylog.DefaultMetadata = activitylogDescMetadata.Default.(func() map[string]interface{})
	backendMixin := schema.Backend{}.Mixin()
	backendMixinFields0 := backendMixin[0].Fields()
	_ = backendMixinFields0
	backendFields := schema.Backend{}.Fields()
	_ = backendFields
	// backendDescCreatedAt is the schema descriptor for created_at field.
	backendDescCreatedAt := backendMixinFields0[0].Descriptor()
	// backend.DefaultCreatedAt holds the default value on creation for the created_at field.
	backend.DefaultCreatedAt = backendDescCreatedAt.Default.(func() time.Time)
	// backendDescUpdatedAt is the schema descriptor for updated_at field.
	backendDescUpdatedAt := backendMixinFields0[1].Descriptor()
	// backend.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backend.DefaultUpdatedAt = backendDescUpdatedAt.Default.(func() time.Time)
	// backend.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backend.UpdateDefaultUpdatedAt = backendDescUpdatedAt.UpdateDefault.(func() time.Time)
	// backendDescName is the schema descriptor for name field.
	backendDescName := backendFields[0].Descriptor()
	// backend.NameValidator is a validator for the "name" field. It is called by the builders before save.
	backend.NameValidator = backendDescName.Validators[0].(func(string) error)
	// backendDescScope is the schema descriptor for scope field.
	backendDescScope := backendFields[1].Descriptor()
	// backend.DefaultScope holds the default value on creation for the scope field.
	backend.DefaultScope = backendDescScope.Default.(string)
	// backendDescOwnerUserID is the schema descriptor for owner_user_id field.
	backendDescOwnerUserID := backendFields[2].Descriptor()
	// backend.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	backend.OwnerUserIDValidator = backendDescOwnerUserID.Validators[0].(func(int) error)
	// backendDescOwnerOrgID is the schema descriptor for owner_org_id field.
	backendDescOwnerOrgID := backendFields[3].Descriptor()
	// backend.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	backend.OwnerOrgIDValidator = backendDescOwnerOrgID.Validators[0].(func(int) error)
	// backendDescOptions is the schema descriptor for options field.
	backendDescOptions := backendFields[5].Descriptor()
	// backend.DefaultOptions holds the default value on creation for the options field.
	backend.DefaultOptions = backendDescOptions.Default.(func() map[string]interface{})
	// backendDescRateLimitPerMinute is the schema descriptor for rate_limit_per_minute field.
	backendDescRateLimitPerMinute := backendFields[6].Descriptor()
	// backend.DefaultRateLimitPerMinute holds the default value on creation for the rate_limit_per_minute field.
	backend.DefaultRateLimitPerMinute = backendDescRateLimitPerMinute.Default.(int)
	bootstrapprompttemplateMixin := schema.BootstrapPromptTemplate{}.Mixin()
	bootstrapprompttemplateMixinFields0 := bootstrapprompttemplateMixin[0].Fields()
	_ = bootstrapprompttemplateMixinFields0
	bootstrapprompttemplateFields := schema.BootstrapPromptTemplate{}.Fields()
	_ = bootstrapprompttemplateFields
	// bootstrapprompttemplateDescCreatedAt is the schema descriptor for created_at field.
	bootstrapprompttemplateDescCreatedAt := bootstrapprompttemplateMixinFields0[0].Descriptor()
	// bootstrapprompttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	bootstrapprompttemplate.DefaultCreatedAt = bootstrapprompttemplateDescCreatedAt.Default.(func() time.Time)
	// bootstrapprompttemplateDescUpdatedAt is the schema descriptor for updated_at field.
	bootstrapprompttemplateDescUpdatedAt := bootstrapprompttemplateMixinFields0[1].Descriptor()
	// bootstrapprompttemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bootstrapprompttemplate.DefaultUpdatedAt = bootstrapprompttemplateDescUpdatedAt.Default.(func() time.Time)
	// bootstrapprompttemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bootstrapprompttemplate.UpdateDefaultUpdatedAt = bootstrapprompttemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bootstrapprompttemplateDescName is the schema descriptor for name field.
	bootstrapprompttemplateDescName := bootstrapprompttemplateFields[0].Descriptor()
	// bootstrapprompttemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bootstrapprompttemplate.NameValidator = bootstrapprompttemplateDescName.Validators[0].(func(string) error)
	// bootstrapprompttemplateDescDescription is the schema descriptor for description field.
	bootstrapprompttemplateDescDescription := bootstrapprompttemplateFields[1].Descriptor()
	// bootstrapprompttemplate.DefaultDescription holds the default value on creation for the description field.
	bootstrapprompttemplate.DefaultDescription = bootstrapprompttemplateDescDescription.Default.(string)
	// bootstrapprompttemplateDescScope is the schema descriptor for scope field.
	bootstrapprompttemplateDescScope := bootstrapprompttemplateFields[2].Descriptor()
	// bootstrapprompttemplate.DefaultScope holds the default value on creation for the scope field.
	bootstrapprompttemplate.DefaultScope = bootstrapprompttemplateDescScope.Default.(string)
	// bootstrapprompttemplateDescOwnerUserID is the schema descriptor for owner_user_id field.
	bootstrapprompttemplateDescOwnerUserID := bootstrapprompttemplateFields[3].Descriptor()
	// bootstrapprompttemplate.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	bootstrapprompttemplate.OwnerUserIDValidator = bootstrapprompttemplateDescOwnerUserID.Validators[0].(func(int) error)
	// bootstrapprompttemplateDescOwnerOrgID is the schema descriptor for owner_org_id field.
	bootstrapprompttemplateDescOwnerOrgID := bootstrapprompttemplateFields[4].Descriptor()
	// bootstrapprompttemplate.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	bootstrapprompttemplate.OwnerOrgIDValidator = bootstrapprompttemplateDescOwnerOrgID.Validators[0].(func(int) error)
	// bootstrapprompttemplateDescContent is the schema descriptor for content field.
	bootstrapprompttemplateDescContent := bootstrapprompttemplateFields[5].Descriptor()
	// bootstrapprompttemplate.DefaultContent holds the default value on creation for the content field.
	bootstrapprompttemplate.DefaultContent = bootstrapprompttemplateDescContent.Default.(string)
	executionplantemplateMixin := schema.ExecutionPlanTemplate{}.Mixin()
	executionplantemplateMixinFields0 := executionplantemplateMixin[0].Fields()
	_ = executionplantemplateMixinFields0
	executionplantemplateFields := schema.ExecutionPlanTemplate{}.Fields()
	_ = executionplantemplateFields
	// executionplantemplateDescCreatedAt is the schema descriptor for created_at field.
	executionplantemplateDescCreatedAt := executionplantemplateMixinFields0[0].Descriptor()
	// executionplantemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	executionplantemplate.DefaultCreatedAt = executionplantemplateDescCreatedAt.Default.(func() time.Time)
	// executionplantemplateDescUpdatedAt is the schema descriptor for updated_at field.
	executionplantemplateDescUpdatedAt := executionplantemplateMixinFields0[1].Descriptor()
	// executionplantemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	executionplantemplate.DefaultUpdatedAt = executionplantemplateDescUpdatedAt.Default.(func() time.Time)
	// executionplantemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	executionplantemplate.UpdateDefaultUpdatedAt = executionplantemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// executionplantemplateDescName is the schema descriptor for name field.
	executionplantemplateDescName := executionplantemplateFields[0].Descriptor()
	// executionplantemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	executionplantemplate.NameValidator = executionplantemplateDescName.Validators[0].(func(string) error)
	// executionplantemplateDescDescription is the schema descriptor for description field.
	executionplantemplateDescDescription := executionplantemplateFields[1].Descriptor()
	// executionplantemplate.DefaultDescription holds the default value on creation for the description field.
	executionplantemplate.DefaultDescription = executionplantemplateDescDescription.Default.(string)
	// executionplantemplateDescScope is the schema descriptor for scope field.
	executionplantemplateDescScope := executionplantemplateFields[2].Descriptor()
	// executionplantemplate.DefaultScope holds the default value on creation for the scope field.
	executionplantemplate.DefaultScope = executionplantemplateDescScope.Default.(string)
	// executionplantemplateDescOwnerUserID is the schema descriptor for owner_user_id field.
	executionplantemplateDescOwnerUserID := executionplantemplateFields[3].Descriptor()
	// executionplantemplate.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	executionplantemplate.OwnerUserIDValidator = executionplantemplateDescOwnerUserID.Validators[0].(func(int) error)
	// executionplantemplateDescOwnerOrgID is the schema descriptor for owner_org_id field.
	executionplantemplateDescOwnerOrgID := executionplantemplateFields[4].Descriptor()
	// executionplantemplate.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	executionplantemplate.OwnerOrgIDValidator = executionplantemplateDescOwnerOrgID.Validators[0].(func(int) error)
	glossaryentryMixin := schema.GlossaryEntry{}.Mixin()
	glossaryentryMixinFields0 := glossaryentryMixin[0].Fields()
	_ = glossaryentryMixinFields0
	glossaryentryFields := schema.GlossaryEntry{}.Fields()
	_ = glossaryentryFields
	// glossaryentryDescCreatedAt is the schema descriptor for created_at field.
	glossaryentryDescCreatedAt := glossaryentryMixinFields0[0].Descriptor()
	// glossaryentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	glossaryentry.DefaultCreatedAt = glossaryentryDescCreatedAt.Default.(func() time.Time)
	// glossaryentryDescUpdatedAt is the schema descriptor for updated_at field.
	glossaryentryDescUpdatedAt := glossaryentryMixinFields0[1].Descriptor()
	// glossaryentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	glossaryentry.DefaultUpdatedAt = glossaryentryDescUpdatedAt.Default.(func() time.Time)
	// glossaryentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	glossaryentry.UpdateDefaultUpdatedAt = glossaryentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// glossaryentryDescSourceKey is the schema descriptor for source_key field.
	glossaryentryDescSourceKey := glossaryentryFields[0].Descriptor()
	// glossaryentry.SourceKeyValidator is a validator for the "source_key" field. It is called by the builders before save.
	glossaryentry.SourceKeyValidator = glossaryentryDescSourceKey.Validators[0].(func(string) error)
	// glossaryentryDescSource is the schema descriptor for source field.
	glossaryentryDescSource := glossaryentryFields[1].Descriptor()
	// glossaryentry.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	glossaryentry.SourceValidator = glossaryentryDescSource.Validators[0].(func(string) error)
	// glossaryentryDescTarget is the schema descriptor for target field.
	glossaryentryDescTarget := glossaryentryFields[2].Descriptor()
	// glossaryentry.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	glossaryentry.TargetValidator = glossaryentryDescTarget.Validators[0].(func(string) error)
	// glossaryentryDescCaseSensitive is the schema descriptor for case_sensitive field.
	glossaryentryDescCaseSensitive := glossaryentryFields[3].Descriptor()
	// glossaryentry.DefaultCaseSensitive holds the default value on creation for the case_sensitive field.
	glossaryentry.DefaultCaseSensitive = glossaryentryDescCaseSensitive.Default.(bool)
	// glossaryentryDescProjectID is the schema descriptor for project_id field.
	glossaryentryDescProjectID := glossaryentryFields[5].Descriptor()
	// glossaryentry.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	glossaryentry.ProjectIDValidator = glossaryentryDescProjectID.Validators[0].(func(int) error)
	jobMixin := schema.Job{}.Mixin()
	jobMixinFields0 := jobMixin[0].Fields()
	_ = jobMixinFields0
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobMixinFields0[0].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobMixinFields0[1].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobDescProjectID is the schema descriptor for project_id field.
	jobDescProjectID := jobFields[0].Descriptor()
	// job.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	job.ProjectIDValidator = jobDescProjectID.Validators[0].(func(int) error)
	// jobDescStatus is the schema descriptor for status field.
	jobDescStatus := jobFields[1].Descriptor()
	// job.DefaultStatus holds the default value on creation for the status field.
	job.DefaultStatus = jobDescStatus.Default.(string)
	// jobDescTriggerType is the schema descriptor for trigger_type field.
	jobDescTriggerType := jobFields[2].Descriptor()
	// job.DefaultTriggerType holds the default value on creation for the trigger_type field.
	job.DefaultTriggerType = jobDescTriggerType.Default.(string)
	// jobDescExecutionPlanID is the schema descriptor for execution_plan_id field.
	jobDescExecutionPlanID := jobFields[3].Descriptor()
	// job.ExecutionPlanIDValidator is a validator for the "execution_plan_id" field. It is called by the builders before save.
	job.ExecutionPlanIDValidator = jobDescExecutionPlanID.Validators[0].(func(int) error)
	// jobDescTranslationConfig is the schema descriptor for translation_config field.
	jobDescTranslationConfig := jobFields[4].Descriptor()
	// job.DefaultTranslationConfig holds the default value on creation for the translation_config field.
	job.DefaultTranslationConfig = jobDescTranslationConfig.Default.(func() map[string]interface{})
	// jobDescResourceCount is the schema descriptor for resource_count field.
	jobDescResourceCount := jobFields[5].Descriptor()
	// job.DefaultResourceCount holds the default value on creation for the resource_count field.
	job.DefaultResourceCount = jobDescResourceCount.Default.(int)
	// job.ResourceCountValidator is a validator for the "resource_count" field. It is called by the builders before save.
	job.ResourceCountValidator = jobDescResourceCount.Validators[0].(func(int) error)
	// jobDescCompletedResources is the schema descriptor for completed_resources field.
	jobDescCompletedResources := jobFields[6].Descriptor()
	// job.DefaultCompletedResources holds the default value on creation for the completed_resources field.
	job.DefaultCompletedResources = jobDescCompletedResources.Default.(int)
	// job.CompletedResourcesValidator is a validator for the "completed_resources" field. It is called by the builders before save.
	job.CompletedResourcesValidator = jobDescCompletedResources.Validators[0].(func(int) error)
	// jobDescFailedResources is the schema descriptor for failed_resources field.
	jobDescFailedResources := jobFields[7].Descriptor()
	// job.DefaultFailedResources holds the default value on creation for the failed_resources field.
	job.DefaultFailedResources = jobDescFailedResources.Default.(int)
	// job.FailedResourcesValidator is a validator for the "failed_resources" field. It is called by the builders before save.
	job.FailedResourcesValidator = jobDescFailedResources.Validators[0].(func(int) error)
	// jobDescTotalSegments is the schema descriptor for total_segments field.
	jobDescTotalSegments := jobFields[8].Descriptor()
	// job.DefaultTotalSegments holds the default value on creation for the total_segments field.
	job.DefaultTotalSegments = jobDescTotalSegments.Default.(int)
	// job.TotalSegmentsValidator is a validator for the "total_segments" field. It is called by the builders before save.
	job.TotalSegmentsValidator = jobDescTotalSegments.Validators[0].(func(int) error)
	// jobDescSkippedSegments is the schema descriptor for skipped_segments field.
	jobDescSkippedSegments := jobFields[9].Descriptor()
	// job.DefaultSkippedSegments holds the default value on creation for the skipped_segments field.
	job.DefaultSkippedSegments = jobDescSkippedSegments.Default.(int)
	// job.SkippedSegmentsValidator is a validator for the "skipped_segments" field. It is called by the builders before save.
	job.SkippedSegmentsValidator = jobDescSkippedSegments.Validators[0].(func(int) error)
	// jobDescStageTotal is the schema descriptor for stage_total field.
	jobDescStageTotal := jobFields[10].Descriptor()
	// job.DefaultStageTotal holds the default value on creation for the stage_total field.
	job.DefaultStageTotal = jobDescStageTotal.Default.(int)
	// job.StageTotalValidator is a validator for the "stage_total" field. It is called by the builders before save.
	job.StageTotalValidator = jobDescStageTotal.Validators[0].(func(int) error)
	// jobDescCompletedSegments is the schema descriptor for completed_segments field.
	jobDescCompletedSegments := jobFields[11].Descriptor()
	// job.DefaultCompletedSegments holds the default value on creation for the completed_segments field.
	job.DefaultCompletedSegments = jobDescCompletedSegments.Default.(int)
	// job.CompletedSegmentsValidator is a validator for the "completed_segments" field. It is called by the builders before save.
	job.CompletedSegmentsValidator = jobDescCompletedSegments.Validators[0].(func(int) error)
	jobresourceMixin := schema.JobResource{}.Mixin()
	jobresourceMixinFields0 := jobresourceMixin[0].Fields()
	_ = jobresourceMixinFields0
	jobresourceFields := schema.JobResource{}.Fields()
	_ = jobresourceFields
	// jobresourceDescCreatedAt is the schema descriptor for created_at field.
	jobresourceDescCreatedAt := jobresourceMixinFields0[0].Descriptor()
	// jobresource.DefaultCreatedAt holds the default value on creation for the created_at field.
	jobresource.DefaultCreatedAt = jobresourceDescCreatedAt.Default.(func() time.Time)
	// jobresourceDescUpdatedAt is the schema descriptor for updated_at field.
	jobresourceDescUpdatedAt := jobresourceMixinFields0[1].Descriptor()
	// jobresource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	jobresource.DefaultUpdatedAt = jobresourceDescUpdatedAt.Default.(func() time.Time)
	// jobresource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	jobresource.UpdateDefaultUpdatedAt = jobresourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobresourceDescStatus is the schema descriptor for status field.
	jobresourceDescStatus := jobresourceFields[0].Descriptor()
	// jobresource.DefaultStatus holds the default value on creation for the status field.
	jobresource.DefaultStatus = jobresourceDescStatus.Default.(string)
	// jobresourceDescSegmentIds is the schema descriptor for segment_ids field.
	jobresourceDescSegmentIds := jobresourceFields[1].Descriptor()
	// jobresource.DefaultSegmentIds holds the default value on creation for the segment_ids field.
	jobresource.DefaultSegmentIds = jobresourceDescSegmentIds.Default.(func() []int)
	// jobresourceDescSegmentCount is the schema descriptor for segment_count field.
	jobresourceDescSegmentCount := jobresourceFields[2].Descriptor()
	// jobresource.DefaultSegmentCount holds the default value on creation for the segment_count field.
	jobresource.DefaultSegmentCount = jobresourceDescSegmentCount.Default.(int)
	// jobresource.SegmentCountValidator is a validator for the "segment_count" field. It is called by the builders before save.
	jobresource.SegmentCountValidator = jobresourceDescSegmentCount.Validators[0].(func(int) error)
	// jobresourceDescCompletedSegments is the schema descriptor for completed_segments field.
	jobresourceDescCompletedSegments := jobresourceFields[3].Descriptor()
	// jobresource.DefaultCompletedSegments holds the default value on creation for the completed_segments field.
	jobresource.DefaultCompletedSegments = jobresourceDescCompletedSegments.Default.(int)
	// jobresource.CompletedSegmentsValidator is a validator for the "completed_segments" field. It is called by the builders before save.
	jobresource.CompletedSegmentsValidator = jobresourceDescCompletedSegments.Validators[0].(func(int) error)
	// jobresourceDescSkippedSegments is the schema descriptor for skipped_segments field.
	jobresourceDescSkippedSegments := jobresourceFields[4].Descriptor()
	// jobresource.DefaultSkippedSegments holds the default value on creation for the skipped_segments field.
	jobresource.DefaultSkippedSegments = jobresourceDescSkippedSegments.Default.(int)
	// jobresource.SkippedSegmentsValidator is a validator for the "skipped_segments" field. It is called by the builders before save.
	jobresource.SkippedSegmentsValidator = jobresourceDescSkippedSegments.Validators[0].(func(int) error)
	// jobresourceDescCurrentStage is the schema descriptor for current_stage field.
	jobresourceDescCurrentStage := jobresourceFields[7].Descriptor()
	// jobresource.DefaultCurrentStage holds the default value on creation for the current_stage field.
	jobresource.DefaultCurrentStage = jobresourceDescCurrentStage.Default.(string)
	// jobresourceDescStageTotal is the schema descriptor for stage_total field.
	jobresourceDescStageTotal := jobresourceFields[8].Descriptor()
	// jobresource.DefaultStageTotal holds the default value on creation for the stage_total field.
	jobresource.DefaultStageTotal = jobresourceDescStageTotal.Default.(int)
	// jobresource.StageTotalValidator is a validator for the "stage_total" field. It is called by the builders before save.
	jobresource.StageTotalValidator = jobresourceDescStageTotal.Validators[0].(func(int) error)
	// jobresourceDescStageCompleted is the schema descriptor for stage_completed field.
	jobresourceDescStageCompleted := jobresourceFields[9].Descriptor()
	// jobresource.DefaultStageCompleted holds the default value on creation for the stage_completed field.
	jobresource.DefaultStageCompleted = jobresourceDescStageCompleted.Default.(int)
	// jobresource.StageCompletedValidator is a validator for the "stage_completed" field. It is called by the builders before save.
	jobresource.StageCompletedValidator = jobresourceDescStageCompleted.Validators[0].(func(int) error)
	orgmembershipMixin := schema.OrgMembership{}.Mixin()
	orgmembershipMixinFields0 := orgmembershipMixin[0].Fields()
	_ = orgmembershipMixinFields0
	orgmembershipFields := schema.OrgMembership{}.Fields()
	_ = orgmembershipFields
	// orgmembershipDescCreatedAt is the schema descriptor for created_at field.
	orgmembershipDescCreatedAt := orgmembershipMixinFields0[0].Descriptor()
	// orgmembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	orgmembership.DefaultCreatedAt = orgmembershipDescCreatedAt.Default.(func() time.Time)
	// orgmembershipDescUpdatedAt is the schema descriptor for updated_at field.
	orgmembershipDescUpdatedAt := orgmembershipMixinFields0[1].Descriptor()
	// orgmembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orgmembership.DefaultUpdatedAt = orgmembershipDescUpdatedAt.Default.(func() time.Time)
	// orgmembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orgmembership.UpdateDefaultUpdatedAt = orgmembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orgmembershipDescRole is the schema descriptor for role field.
	orgmembershipDescRole := orgmembershipFields[0].Descriptor()
	// orgmembership.DefaultRole holds the default value on creation for the role field.
	orgmembership.DefaultRole = orgmembershipDescRole.Default.(string)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[1].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	projectMixin := schema.Project{}.Mixin()
	projectMixinFields0 := projectMixin[0].Fields()
	_ = projectMixinFields0
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectMixinFields0[0].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectMixinFields0[1].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescOwnerUserID is the schema descriptor for owner_user_id field.
	projectDescOwnerUserID := projectFields[1].Descriptor()
	// project.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	project.OwnerUserIDValidator = projectDescOwnerUserID.Validators[0].(func(int) error)
	// projectDescOwnerOrgID is the schema descriptor for owner_org_id field.
	projectDescOwnerOrgID := projectFields[2].Descriptor()
	// project.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	project.OwnerOrgIDValidator = projectDescOwnerOrgID.Validators[0].(func(int) error)
	// projectDescConfig is the schema descriptor for config field.
	projectDescConfig := projectFields[3].Descriptor()
	// project.DefaultConfig holds the default value on creation for the config field.
	project.DefaultConfig = projectDescConfig.Default.(func() map[string]interface{})
	// projectDescDefaultTranslationConfig is the schema descriptor for default_translation_config field.
	projectDescDefaultTranslationConfig := projectFields[4].Descriptor()
	// project.DefaultDefaultTranslationConfig holds the default value on creation for the default_translation_config field.
	project.DefaultDefaultTranslationConfig = projectDescDefaultTranslationConfig.Default.(func() map[string]interface{})
	// projectDescGlossaryEnabled is the schema descriptor for glossary_enabled field.
	projectDescGlossaryEnabled := projectFields[5].Descriptor()
	// project.DefaultGlossaryEnabled holds the default value on creation for the glossary_enabled field.
	project.DefaultGlossaryEnabled = projectDescGlossaryEnabled.Default.(bool)
	// projectDescSourceLang is the schema descriptor for source_lang field.
	projectDescSourceLang := projectFields[6].Descriptor()
	// project.DefaultSourceLang holds the default value on creation for the source_lang field.
	project.DefaultSourceLang = projectDescSourceLang.Default.(string)
	// projectDescTargetLang is the schema descriptor for target_lang field.
	projectDescTargetLang := projectFields[7].Descriptor()
	// project.DefaultTargetLang holds the default value on creation for the target_lang field.
	project.DefaultTargetLang = projectDescTargetLang.Default.(string)
	refreshtokenMixin := schema.RefreshToken{}.Mixin()
	refreshtokenMixinFields0 := refreshtokenMixin[0].Fields()
	_ = refreshtokenMixinFields0
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenMixinFields0[0].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	refreshtokenDescUpdatedAt := refreshtokenMixinFields0[1].Descriptor()
	// refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshtoken.DefaultUpdatedAt = refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshtoken.UpdateDefaultUpdatedAt = refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[0].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = refreshtokenDescTokenHash.Validators[0].(func(string) error)
	resourceMixin := schema.Resource{}.Mixin()
	resourceMixinFields0 := resourceMixin[0].Fields()
	_ = resourceMixinFields0
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceMixinFields0[0].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceMixinFields0[1].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourceDescPath is the schema descriptor for path field.
	resourceDescPath := resourceFields[0].Descriptor()
	// resource.PathValidator is a validator for the "path" field. It is called by the builders before save.
	resource.PathValidator = resourceDescPath.Validators[0].(func(string) error)
	// resourceDescFormat is the schema descriptor for format field.
	resourceDescFormat := resourceFields[1].Descriptor()
	// resource.FormatValidator is a validator for the "format" field. It is called by the builders before save.
	resource.FormatValidator = resourceDescFormat.Validators[0].(func(string) error)
	// resourceDescStoragePath is the schema descriptor for storage_path field.
	resourceDescStoragePath := resourceFields[2].Descriptor()
	// resource.StoragePathValidator is a validator for the "storage_path" field. It is called by the builders before save.
	resource.StoragePathValidator = resourceDescStoragePath.Validators[0].(func(string) error)
	// resourceDescTotalSegments is the schema descriptor for total_segments field.
	resourceDescTotalSegments := resourceFields[3].Descriptor()
	// resource.DefaultTotalSegments holds the default value on creation for the total_segments field.
	resource.DefaultTotalSegments = resourceDescTotalSegments.Default.(int)
	// resource.TotalSegmentsValidator is a validator for the "total_segments" field. It is called by the builders before save.
	resource.TotalSegmentsValidator = resourceDescTotalSegments.Validators[0].(func(int) error)
	// resourceDescProjectID is the schema descriptor for project_id field.
	resourceDescProjectID := resourceFields[4].Descriptor()
	// resource.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	resource.ProjectIDValidator = resourceDescProjectID.Validators[0].(func(int) error)
	sseeventFields := schema.SSEEvent{}.Fields()
	_ = sseeventFields
	// sseeventDescJobID is the schema descriptor for job_id field.
	sseeventDescJobID := sseeventFields[0].Descriptor()
	// sseevent.JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	sseevent.JobIDValidator = sseeventDescJobID.Validators[0].(func(int) error)
	// sseeventDescSeq is the schema descriptor for seq field.
	sseeventDescSeq := sseeventFields[1].Descriptor()
	// sseevent.SeqValidator is a validator for the "seq" field. It is called by the builders before save.
	sseevent.SeqValidator = sseeventDescSeq.Validators[0].(func(int64) error)
	// sseeventDescCreatedAt is the schema descriptor for created_at field.
	sseeventDescCreatedAt := sseeventFields[7].Descriptor()
	// sseevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	sseevent.DefaultCreatedAt = sseeventDescCreatedAt.Default.(func() time.Time)
	segmentMixin := schema.Segment{}.Mixin()
	segmentMixinFields0 := segmentMixin[0].Fields()
	_ = segmentMixinFields0
	segmentFields := schema.Segment{}.Fields()
	_ = segmentFields
	// segmentDescCreatedAt is the schema descriptor for created_at field.
	segmentDescCreatedAt := segmentMixinFields0[0].Descriptor()
	// segment.DefaultCreatedAt holds the default value on creation for the created_at field.
	segment.DefaultCreatedAt = segmentDescCreatedAt.Default.(func() time.Time)
	// segmentDescUpdatedAt is the schema descriptor for updated_at field.
	segmentDescUpdatedAt := segmentMixinFields0[1].Descriptor()
	// segment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	segment.DefaultUpdatedAt = segmentDescUpdatedAt.Default.(func() time.Time)
	// segment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	segment.UpdateDefaultUpdatedAt = segmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// segmentDescSegmentIndex is the schema descriptor for segment_index field.
	segmentDescSegmentIndex := segmentFields[0].Descriptor()
	// segment.SegmentIndexValidator is a validator for the "segment_index" field. It is called by the builders before save.
	segment.SegmentIndexValidator = segmentDescSegmentIndex.Validators[0].(func(int) error)
	// segmentDescSourceText is the schema descriptor for source_text field.
	segmentDescSourceText := segmentFields[1].Descriptor()
	// segment.SourceTextValidator is a validator for the "source_text" field. It is called by the builders before save.
	segment.SourceTextValidator = segmentDescSourceText.Validators[0].(func(string) error)
	// segmentDescResourceID is the schema descriptor for resource_id field.
	segmentDescResourceID := segmentFields[5].Descriptor()
	// segment.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	segment.ResourceIDValidator = segmentDescResourceID.Validators[0].(func(int) error)
	synctaskMixin := schema.SyncTask{}.Mixin()
	synctaskMixinFields0 := synctaskMixin[0].Fields()
	_ = synctaskMixinFields0
	synctaskFields := schema.SyncTask{}.Fields()
	_ = synctaskFields
	// synctaskDescCreatedAt is the schema descriptor for created_at field.
	synctaskDescCreatedAt := synctaskMixinFields0[0].Descriptor()
	// synctask.DefaultCreatedAt holds the default value on creation for the created_at field.
	synctask.DefaultCreatedAt = synctaskDescCreatedAt.Default.(func() time.Time)
	// synctaskDescUpdatedAt is the schema descriptor for updated_at field.
	synctaskDescUpdatedAt := synctaskMixinFields0[1].Descriptor()
	// synctask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	synctask.DefaultUpdatedAt = synctaskDescUpdatedAt.Default.(func() time.Time)
	// synctask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	synctask.UpdateDefaultUpdatedAt = synctaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// synctaskDescProjectID is the schema descriptor for project_id field.
	synctaskDescProjectID := synctaskFields[0].Descriptor()
	// synctask.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	synctask.ProjectIDValidator = synctaskDescProjectID.Validators[0].(func(int) error)
	// synctaskDescEntryID is the schema descriptor for entry_id field.
	synctaskDescEntryID := synctaskFields[1].Descriptor()
	// synctask.EntryIDValidator is a validator for the "entry_id" field. It is called by the builders before save.
	synctask.EntryIDValidator = synctaskDescEntryID.Validators[0].(func(int) error)
	// synctaskDescActorUserID is the schema descriptor for actor_user_id field.
	synctaskDescActorUserID := synctaskFields[2].Descriptor()
	// synctask.ActorUserIDValidator is a validator for the "actor_user_id" field. It is called by the builders before save.
	synctask.ActorUserIDValidator = synctaskDescActorUserID.Validators[0].(func(int) error)
	// synctaskDescOldTarget is the schema descriptor for old_target field.
	synctaskDescOldTarget := synctaskFields[3].Descriptor()
	// synctask.OldTargetValidator is a validator for the "old_target" field. It is called by the builders before save.
	synctask.OldTargetValidator = synctaskDescOldTarget.Validators[0].(func(string) error)
	// synctaskDescNewTarget is the schema descriptor for new_target field.
	synctaskDescNewTarget := synctaskFields[4].Descriptor()
	// synctask.NewTargetValidator is a validator for the "new_target" field. It is called by the builders before save.
	synctask.NewTargetValidator = synctaskDescNewTarget.Validators[0].(func(string) error)
	// synctaskDescTotalSegments is the schema descriptor for total_segments field.
	synctaskDescTotalSegments := synctaskFields[5].Descriptor()
	// synctask.TotalSegmentsValidator is a validator for the "total_segments" field. It is called by the builders before save.
	synctask.TotalSegmentsValidator = synctaskDescTotalSegments.Validators[0].(func(int) error)
	// synctaskDescProcessedSegments is the schema descriptor for processed_segments field.
	synctaskDescProcessedSegments := synctaskFields[6].Descriptor()
	// synctask.DefaultProcessedSegments holds the default value on creation for the processed_segments field.
	synctask.DefaultProcessedSegments = synctaskDescProcessedSegments.Default.(int)
	// synctask.ProcessedSegmentsValidator is a validator for the "processed_segments" field. It is called by the builders before save.
	synctask.ProcessedSegmentsValidator = synctaskDescProcessedSegments.Validators[0].(func(int) error)
	// synctaskDescStatus is the schema descriptor for status field.
	synctaskDescStatus := synctaskFields[7].Descriptor()
	// synctask.DefaultStatus holds the default value on creation for the status field.
	synctask.DefaultStatus = synctaskDescStatus.Default.(string)
	// synctask.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	synctask.StatusValidator = synctaskDescStatus.Validators[0].(func(string) error)
	systemsettingMixin := schema.SystemSetting{}.Mixin()
	systemsettingMixinFields0 := systemsettingMixin[0].Fields()
	_ = systemsettingMixinFields0
	systemsettingFields := schema.SystemSetting{}.Fields()
	_ = systemsettingFields
	// systemsettingDescCreatedAt is the schema descriptor for created_at field.
	systemsettingDescCreatedAt := systemsettingMixinFields0[0].Descriptor()
	// systemsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemsetting.DefaultCreatedAt = systemsettingDescCreatedAt.Default.(func() time.Time)
	// systemsettingDescUpdatedAt is the schema descriptor for updated_at field.
	systemsettingDescUpdatedAt := systemsettingMixinFields0[1].Descriptor()
	// systemsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemsetting.DefaultUpdatedAt = systemsettingDescUpdatedAt.Default.(func() time.Time)
	// systemsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemsetting.UpdateDefaultUpdatedAt = systemsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemsettingDescKey is the schema descriptor for key field.
	systemsettingDescKey := systemsettingFields[0].Descriptor()
	// systemsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemsetting.KeyValidator = systemsettingDescKey.Validators[0].(func(string) error)
	tmentryMixin := schema.TMEntry{}.Mixin()
	tmentryMixinFields0 := tmentryMixin[0].Fields()
	_ = tmentryMixinFields0
	tmentryFields := schema.TMEntry{}.Fields()
	_ = tmentryFields
	// tmentryDescCreatedAt is the schema descriptor for created_at field.
	tmentryDescCreatedAt := tmentryMixinFields0[0].Descriptor()
	// tmentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	tmentry.DefaultCreatedAt = tmentryDescCreatedAt.Default.(func() time.Time)
	// tmentryDescUpdatedAt is the schema descriptor for updated_at field.
	tmentryDescUpdatedAt := tmentryMixinFields0[1].Descriptor()
	// tmentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tmentry.DefaultUpdatedAt = tmentryDescUpdatedAt.Default.(func() time.Time)
	// tmentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tmentry.UpdateDefaultUpdatedAt = tmentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tmentryDescScopeKey is the schema descriptor for scope_key field.
	tmentryDescScopeKey := tmentryFields[0].Descriptor()
	// tmentry.ScopeKeyValidator is a validator for the "scope_key" field. It is called by the builders before save.
	tmentry.ScopeKeyValidator = tmentryDescScopeKey.Validators[0].(func(string) error)
	// tmentryDescSourceHash is the schema descriptor for source_hash field.
	tmentryDescSourceHash := tmentryFields[1].Descriptor()
	// tmentry.SourceHashValidator is a validator for the "source_hash" field. It is called by the builders before save.
	tmentry.SourceHashValidator = tmentryDescSourceHash.Validators[0].(func(string) error)
	// tmentryDescSourceText is the schema descriptor for source_text field.
	tmentryDescSourceText := tmentryFields[2].Descriptor()
	// tmentry.SourceTextValidator is a validator for the "source_text" field. It is called by the builders before save.
	tmentry.SourceTextValidator = tmentryDescSourceText.Validators[0].(func(string) error)
	// tmentryDescTargetText is the schema descriptor for target_text field.
	tmentryDescTargetText := tmentryFields[3].Descriptor()
	// tmentry.TargetTextValidator is a validator for the "target_text" field. It is called by the builders before save.
	tmentry.TargetTextValidator = tmentryDescTargetText.Validators[0].(func(string) error)
	// tmentryDescSourceLang is the schema descriptor for source_lang field.
	tmentryDescSourceLang := tmentryFields[4].Descriptor()
	// tmentry.SourceLangValidator is a validator for the "source_lang" field. It is called by the builders before save.
	tmentry.SourceLangValidator = tmentryDescSourceLang.Validators[0].(func(string) error)
	// tmentryDescTargetLang is the schema descriptor for target_lang field.
	tmentryDescTargetLang := tmentryFields[5].Descriptor()
	// tmentry.TargetLangValidator is a validator for the "target_lang" field. It is called by the builders before save.
	tmentry.TargetLangValidator = tmentryDescTargetLang.Validators[0].(func(string) error)
	// tmentryDescUsageCount is the schema descriptor for usage_count field.
	tmentryDescUsageCount := tmentryFields[6].Descriptor()
	// tmentry.DefaultUsageCount holds the default value on creation for the usage_count field.
	tmentry.DefaultUsageCount = tmentryDescUsageCount.Default.(int)
	// tmentry.UsageCountValidator is a validator for the "usage_count" field. It is called by the builders before save.
	tmentry.UsageCountValidator = tmentryDescUsageCount.Validators[0].(func(int) error)
	// tmentryDescProjectID is the schema descriptor for project_id field.
	tmentryDescProjectID := tmentryFields[7].Descriptor()
	// tmentry.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	tmentry.ProjectIDValidator = tmentryDescProjectID.Validators[0].(func(int) error)
	translationprofileMixin := schema.TranslationProfile{}.Mixin()
	translationprofileMixinFields0 := translationprofileMixin[0].Fields()
	_ = translationprofileMixinFields0
	translationprofileFields := schema.TranslationProfile{}.Fields()
	_ = translationprofileFields
	// translationprofileDescCreatedAt is the schema descriptor for created_at field.
	translationprofileDescCreatedAt := translationprofileMixinFields0[0].Descriptor()
	// translationprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	translationprofile.DefaultCreatedAt = translationprofileDescCreatedAt.Default.(func() time.Time)
	// translationprofileDescUpdatedAt is the schema descriptor for updated_at field.
	translationprofileDescUpdatedAt := translationprofileMixinFields0[1].Descriptor()
	// translationprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	translationprofile.DefaultUpdatedAt = translationprofileDescUpdatedAt.Default.(func() time.Time)
	// translationprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	translationprofile.UpdateDefaultUpdatedAt = translationprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// translationprofileDescName is the schema descriptor for name field.
	translationprofileDescName := translationprofileFields[0].Descriptor()
	// translationprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	translationprofile.NameValidator = translationprofileDescName.Validators[0].(func(string) error)
	// translationprofileDescDescription is the schema descriptor for description field.
	translationprofileDescDescription := translationprofileFields[1].Descriptor()
	// translationprofile.DefaultDescription holds the default value on creation for the description field.
	translationprofile.DefaultDescription = translationprofileDescDescription.Default.(string)
	// translationprofileDescScope is the schema descriptor for scope field.
	translationprofileDescScope := translationprofileFields[2].Descriptor()
	// translationprofile.DefaultScope holds the default value on creation for the scope field.
	translationprofile.DefaultScope = translationprofileDescScope.Default.(string)
	// translationprofileDescOwnerUserID is the schema descriptor for owner_user_id field.
	translationprofileDescOwnerUserID := translationprofileFields[3].Descriptor()
	// translationprofile.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	translationprofile.OwnerUserIDValidator = translationprofileDescOwnerUserID.Validators[0].(func(int) error)
	// translationprofileDescOwnerOrgID is the schema descriptor for owner_org_id field.
	translationprofileDescOwnerOrgID := translationprofileFields[4].Descriptor()
	// translationprofile.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	translationprofile.OwnerOrgIDValidator = translationprofileDescOwnerOrgID.Validators[0].(func(int) error)
	// translationprofileDescConfig is the schema descriptor for config field.
	translationprofileDescConfig := translationprofileFields[5].Descriptor()
	// translationprofile.DefaultConfig holds the default value on creation for the config field.
	translationprofile.DefaultConfig = translationprofileDescConfig.Default.(schema.TranslationProfileConfigData)
	translationprompttemplateMixin := schema.TranslationPromptTemplate{}.Mixin()
	translationprompttemplateMixinFields0 := translationprompttemplateMixin[0].Fields()
	_ = translationprompttemplateMixinFields0
	translationprompttemplateFields := schema.TranslationPromptTemplate{}.Fields()
	_ = translationprompttemplateFields
	// translationprompttemplateDescCreatedAt is the schema descriptor for created_at field.
	translationprompttemplateDescCreatedAt := translationprompttemplateMixinFields0[0].Descriptor()
	// translationprompttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	translationprompttemplate.DefaultCreatedAt = translationprompttemplateDescCreatedAt.Default.(func() time.Time)
	// translationprompttemplateDescUpdatedAt is the schema descriptor for updated_at field.
	translationprompttemplateDescUpdatedAt := translationprompttemplateMixinFields0[1].Descriptor()
	// translationprompttemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	translationprompttemplate.DefaultUpdatedAt = translationprompttemplateDescUpdatedAt.Default.(func() time.Time)
	// translationprompttemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	translationprompttemplate.UpdateDefaultUpdatedAt = translationprompttemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// translationprompttemplateDescName is the schema descriptor for name field.
	translationprompttemplateDescName := translationprompttemplateFields[0].Descriptor()
	// translationprompttemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	translationprompttemplate.NameValidator = translationprompttemplateDescName.Validators[0].(func(string) error)
	// translationprompttemplateDescDescription is the schema descriptor for description field.
	translationprompttemplateDescDescription := translationprompttemplateFields[1].Descriptor()
	// translationprompttemplate.DefaultDescription holds the default value on creation for the description field.
	translationprompttemplate.DefaultDescription = translationprompttemplateDescDescription.Default.(string)
	// translationprompttemplateDescScope is the schema descriptor for scope field.
	translationprompttemplateDescScope := translationprompttemplateFields[2].Descriptor()
	// translationprompttemplate.DefaultScope holds the default value on creation for the scope field.
	translationprompttemplate.DefaultScope = translationprompttemplateDescScope.Default.(string)
	// translationprompttemplateDescOwnerUserID is the schema descriptor for owner_user_id field.
	translationprompttemplateDescOwnerUserID := translationprompttemplateFields[3].Descriptor()
	// translationprompttemplate.OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	translationprompttemplate.OwnerUserIDValidator = translationprompttemplateDescOwnerUserID.Validators[0].(func(int) error)
	// translationprompttemplateDescOwnerOrgID is the schema descriptor for owner_org_id field.
	translationprompttemplateDescOwnerOrgID := translationprompttemplateFields[4].Descriptor()
	// translationprompttemplate.OwnerOrgIDValidator is a validator for the "owner_org_id" field. It is called by the builders before save.
	translationprompttemplate.OwnerOrgIDValidator = translationprompttemplateDescOwnerOrgID.Validators[0].(func(int) error)
	// translationprompttemplateDescSystemPromptContent is the schema descriptor for system_prompt_content field.
	translationprompttemplateDescSystemPromptContent := translationprompttemplateFields[5].Descriptor()
	// translationprompttemplate.DefaultSystemPromptContent holds the default value on creation for the system_prompt_content field.
	translationprompttemplate.DefaultSystemPromptContent = translationprompttemplateDescSystemPromptContent.Default.(string)
	usagerecordMixin := schema.UsageRecord{}.Mixin()
	usagerecordMixinFields0 := usagerecordMixin[0].Fields()
	_ = usagerecordMixinFields0
	usagerecordFields := schema.UsageRecord{}.Fields()
	_ = usagerecordFields
	// usagerecordDescCreatedAt is the schema descriptor for created_at field.
	usagerecordDescCreatedAt := usagerecordMixinFields0[0].Descriptor()
	// usagerecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagerecord.DefaultCreatedAt = usagerecordDescCreatedAt.Default.(func() time.Time)
	// usagerecordDescUpdatedAt is the schema descriptor for updated_at field.
	usagerecordDescUpdatedAt := usagerecordMixinFields0[1].Descriptor()
	// usagerecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usagerecord.DefaultUpdatedAt = usagerecordDescUpdatedAt.Default.(func() time.Time)
	// usagerecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usagerecord.UpdateDefaultUpdatedAt = usagerecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usagerecordDescSource is the schema descriptor for source field.
	usagerecordDescSource := usagerecordFields[0].Descriptor()
	// usagerecord.DefaultSource holds the default value on creation for the source field.
	usagerecord.DefaultSource = usagerecordDescSource.Default.(string)
	// usagerecordDescAPICalls is the schema descriptor for api_calls field.
	usagerecordDescAPICalls := usagerecordFields[1].Descriptor()
	// usagerecord.DefaultAPICalls holds the default value on creation for the api_calls field.
	usagerecord.DefaultAPICalls = usagerecordDescAPICalls.Default.(int)
	// usagerecord.APICallsValidator is a validator for the "api_calls" field. It is called by the builders before save.
	usagerecord.APICallsValidator = usagerecordDescAPICalls.Validators[0].(func(int) error)
	// usagerecordDescInputTokens is the schema descriptor for input_tokens field.
	usagerecordDescInputTokens := usagerecordFields[2].Descriptor()
	// usagerecord.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagerecord.DefaultInputTokens = usagerecordDescInputTokens.Default.(int)
	// usagerecord.InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	usagerecord.InputTokensValidator = usagerecordDescInputTokens.Validators[0].(func(int) error)
	// usagerecordDescOutputTokens is the schema descriptor for output_tokens field.
	usagerecordDescOutputTokens := usagerecordFields[3].Descriptor()
	// usagerecord.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagerecord.DefaultOutputTokens = usagerecordDescOutputTokens.Default.(int)
	// usagerecord.OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	usagerecord.OutputTokensValidator = usagerecordDescOutputTokens.Validators[0].(func(int) error)
	// usagerecordDescSegmentCount is the schema descriptor for segment_count field.
	usagerecordDescSegmentCount := usagerecordFields[4].Descriptor()
	// usagerecord.DefaultSegmentCount holds the default value on creation for the segment_count field.
	usagerecord.DefaultSegmentCount = usagerecordDescSegmentCount.Default.(int)
	// usagerecord.SegmentCountValidator is a validator for the "segment_count" field. It is called by the builders before save.
	usagerecord.SegmentCountValidator = usagerecordDescSegmentCount.Validators[0].(func(int) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[5].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
}
