// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/job"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/sseevent"
)

// SSEEventCreate is the builder for creating a SSEEvent entity.
type SSEEventCreate struct {
	config
	mutation *SSEEventMutation
	hooks    []Hook
}

// SetJobID sets the "job_id" field.
func (_c *SSEEventCreate) SetJobID(v int) *SSEEventCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *SSEEventCreate) SetSeq(v int64) *SSEEventCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SSEEventCreate) SetType(v string) *SSEEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *SSEEventCreate) SetLevel(v string) *SSEEventCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *SSEEventCreate) SetStage(v string) *SSEEventCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *SSEEventCreate) SetNillableStage(v *string) *SSEEventCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *SSEEventCreate) SetMessage(v string) *SSEEventCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SSEEventCreate) SetMetadata(v map[string]interface{}) *SSEEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SSEEventCreate) SetCreatedAt(v time.Time) *SSEEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SSEEventCreate) SetNillableCreatedAt(v *time.Time) *SSEEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetJob sets the "job" edge to the Job entity.
func (_c *SSEEventCreate) SetJob(v *Job) *SSEEventCreate {
	return _c.SetJobID(v.ID)
}

// Mutation returns the SSEEventMutation object of the builder.
func (_c *SSEEventCreate) Mutation() *SSEEventMutation {
	return _c.mutation
}

// Save creates the SSEEvent in the database.
func (_c *SSEEventCreate) Save(ctx context.Context) (*SSEEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SSEEventCreate) SaveX(ctx context.Context) *SSEEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SSEEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SSEEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SSEEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sseevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SSEEventCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "SSEEvent.job_id"`)}
	}
	if v, ok := _c.mutation.JobID(); ok {
		if err := sseevent.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "SSEEvent.job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "SSEEvent.seq"`)}
	}
	if v, ok := _c.mutation.Seq(); ok {
		if err := sseevent.SeqValidator(v); err != nil {
			return &ValidationError{Name: "seq", err: fmt.Errorf(`ent: validator failed for field "SSEEvent.seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SSEEvent.type"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "SSEEvent.level"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "SSEEvent.message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SSEEvent.created_at"`)}
	}
	if len(_c.mutation.JobIDs()) == 0 {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required edge "SSEEvent.job"`)}
	}
	return nil
}

func (_c *SSEEventCreate) sqlSave(ctx context.Context) (*SSEEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SSEEventCreate) createSpec() (*SSEEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SSEEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sseevent.Table, sqlgraph.NewFieldSpec(sseevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(sseevent.FieldSeq, field.TypeInt64, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(sseevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(sseevent.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(sseevent.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(sseevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(sseevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sseevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sseevent.JobTable,
			Columns: []string{sseevent.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SSEEventCreateBulk is the builder for creating many SSEEvent entities in bulk.
type SSEEventCreateBulk struct {
	config
	err      error
	builders []*SSEEventCreate
}

// Save creates the SSEEvent entities in the database.
func (_c *SSEEventCreateBulk) Save(ctx context.Context) ([]*SSEEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SSEEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SSEEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SSEEventCreateBulk) SaveX(ctx context.Context) []*SSEEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SSEEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SSEEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
