// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/storageconnection"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/storagespace"
)

// StorageSpace is the model entity for the StorageSpace schema.
type StorageSpace struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ConnectionID holds the value of the "connection_id" field.
	ConnectionID int `json:"connection_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Identity holds the value of the "identity" field.
	Identity string `json:"identity,omitempty"`
	// MarkerNonce holds the value of the "marker_nonce" field.
	MarkerNonce string `json:"marker_nonce,omitempty"`
	// Bucket holds the value of the "bucket" field.
	Bucket string `json:"bucket,omitempty"`
	// Prefix holds the value of the "prefix" field.
	Prefix string `json:"prefix,omitempty"`
	// OwnerKind holds the value of the "owner_kind" field.
	OwnerKind storagespace.OwnerKind `json:"owner_kind,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// ManagementGeneration holds the value of the "management_generation" field.
	ManagementGeneration int64 `json:"management_generation,omitempty"`
	// Status holds the value of the "status" field.
	Status storagespace.Status `json:"status,omitempty"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// Versioned holds the value of the "versioned" field.
	Versioned bool `json:"versioned,omitempty"`
	// CapacityBytes holds the value of the "capacity_bytes" field.
	CapacityBytes int64 `json:"capacity_bytes,omitempty"`
	// ReservedBytes holds the value of the "reserved_bytes" field.
	ReservedBytes int64 `json:"reserved_bytes,omitempty"`
	// CandidateBytes holds the value of the "candidate_bytes" field.
	CandidateBytes int64 `json:"candidate_bytes,omitempty"`
	// LiveBytes holds the value of the "live_bytes" field.
	LiveBytes int64 `json:"live_bytes,omitempty"`
	// PendingDeleteBytes holds the value of the "pending_delete_bytes" field.
	PendingDeleteBytes int64 `json:"pending_delete_bytes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StorageSpaceQuery when eager-loading is set.
	Edges        StorageSpaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StorageSpaceEdges holds the relations/edges for other nodes in the graph.
type StorageSpaceEdges struct {
	// Connection holds the value of the connection edge.
	Connection *StorageConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageSpaceEdges) ConnectionOrErr() (*StorageConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: storageconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageSpace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storagespace.FieldVerified, storagespace.FieldVersioned:
			values[i] = new(sql.NullBool)
		case storagespace.FieldID, storagespace.FieldConnectionID, storagespace.FieldOwnerID, storagespace.FieldManagementGeneration, storagespace.FieldCapacityBytes, storagespace.FieldReservedBytes, storagespace.FieldCandidateBytes, storagespace.FieldLiveBytes, storagespace.FieldPendingDeleteBytes:
			values[i] = new(sql.NullInt64)
		case storagespace.FieldName, storagespace.FieldIdentity, storagespace.FieldMarkerNonce, storagespace.FieldBucket, storagespace.FieldPrefix, storagespace.FieldOwnerKind, storagespace.FieldStatus:
			values[i] = new(sql.NullString)
		case storagespace.FieldCreatedAt, storagespace.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageSpace fields.
func (_m *StorageSpace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storagespace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case storagespace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case storagespace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case storagespace.FieldConnectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = int(value.Int64)
			}
		case storagespace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case storagespace.FieldIdentity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity", values[i])
			} else if value.Valid {
				_m.Identity = value.String
			}
		case storagespace.FieldMarkerNonce:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field marker_nonce", values[i])
			} else if value.Valid {
				_m.MarkerNonce = value.String
			}
		case storagespace.FieldBucket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.String
			}
		case storagespace.FieldPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prefix", values[i])
			} else if value.Valid {
				_m.Prefix = value.String
			}
		case storagespace.FieldOwnerKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_kind", values[i])
			} else if value.Valid {
				_m.OwnerKind = storagespace.OwnerKind(value.String)
			}
		case storagespace.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = int(value.Int64)
			}
		case storagespace.FieldManagementGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field management_generation", values[i])
			} else if value.Valid {
				_m.ManagementGeneration = value.Int64
			}
		case storagespace.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = storagespace.Status(value.String)
			}
		case storagespace.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = value.Bool
			}
		case storagespace.FieldVersioned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field versioned", values[i])
			} else if value.Valid {
				_m.Versioned = value.Bool
			}
		case storagespace.FieldCapacityBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field capacity_bytes", values[i])
			} else if value.Valid {
				_m.CapacityBytes = value.Int64
			}
		case storagespace.FieldReservedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_bytes", values[i])
			} else if value.Valid {
				_m.ReservedBytes = value.Int64
			}
		case storagespace.FieldCandidateBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_bytes", values[i])
			} else if value.Valid {
				_m.CandidateBytes = value.Int64
			}
		case storagespace.FieldLiveBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field live_bytes", values[i])
			} else if value.Valid {
				_m.LiveBytes = value.Int64
			}
		case storagespace.FieldPendingDeleteBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_delete_bytes", values[i])
			} else if value.Valid {
				_m.PendingDeleteBytes = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageSpace.
// This includes values selected through modifiers, order, etc.
func (_m *StorageSpace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConnection queries the "connection" edge of the StorageSpace entity.
func (_m *StorageSpace) QueryConnection() *StorageConnectionQuery {
	return NewStorageSpaceClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this StorageSpace.
// Note that you need to call StorageSpace.Unwrap() before calling this method if this StorageSpace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageSpace) Update() *StorageSpaceUpdateOne {
	return NewStorageSpaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageSpace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageSpace) Unwrap() *StorageSpace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StorageSpace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageSpace) String() string {
	var builder strings.Builder
	builder.WriteString("StorageSpace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("connection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConnectionID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("identity=")
	builder.WriteString(_m.Identity)
	builder.WriteString(", ")
	builder.WriteString("marker_nonce=")
	builder.WriteString(_m.MarkerNonce)
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket)
	builder.WriteString(", ")
	builder.WriteString("prefix=")
	builder.WriteString(_m.Prefix)
	builder.WriteString(", ")
	builder.WriteString("owner_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerKind))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("management_generation=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManagementGeneration))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verified))
	builder.WriteString(", ")
	builder.WriteString("versioned=")
	builder.WriteString(fmt.Sprintf("%v", _m.Versioned))
	builder.WriteString(", ")
	builder.WriteString("capacity_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CapacityBytes))
	builder.WriteString(", ")
	builder.WriteString("reserved_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedBytes))
	builder.WriteString(", ")
	builder.WriteString("candidate_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateBytes))
	builder.WriteString(", ")
	builder.WriteString("live_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LiveBytes))
	builder.WriteString(", ")
	builder.WriteString("pending_delete_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingDeleteBytes))
	builder.WriteByte(')')
	return builder.String()
}

// StorageSpaces is a parsable slice of StorageSpace.
type StorageSpaces []*StorageSpace
