// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/blob"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/bloblocation"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/storagemigrationitem"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/storagetask"
)

// StorageMigrationItemCreate is the builder for creating a StorageMigrationItem entity.
type StorageMigrationItemCreate struct {
	config
	mutation *StorageMigrationItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *StorageMigrationItemCreate) SetCreatedAt(v time.Time) *StorageMigrationItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StorageMigrationItemCreate) SetNillableCreatedAt(v *time.Time) *StorageMigrationItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StorageMigrationItemCreate) SetUpdatedAt(v time.Time) *StorageMigrationItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StorageMigrationItemCreate) SetNillableUpdatedAt(v *time.Time) *StorageMigrationItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *StorageMigrationItemCreate) SetTaskID(v int) *StorageMigrationItemCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetBlobID sets the "blob_id" field.
func (_c *StorageMigrationItemCreate) SetBlobID(v int) *StorageMigrationItemCreate {
	_c.mutation.SetBlobID(v)
	return _c
}

// SetSourceLocationID sets the "source_location_id" field.
func (_c *StorageMigrationItemCreate) SetSourceLocationID(v int) *StorageMigrationItemCreate {
	_c.mutation.SetSourceLocationID(v)
	return _c
}

// SetTargetLocationID sets the "target_location_id" field.
func (_c *StorageMigrationItemCreate) SetTargetLocationID(v int) *StorageMigrationItemCreate {
	_c.mutation.SetTargetLocationID(v)
	return _c
}

// SetNillableTargetLocationID sets the "target_location_id" field if the given value is not nil.
func (_c *StorageMigrationItemCreate) SetNillableTargetLocationID(v *int) *StorageMigrationItemCreate {
	if v != nil {
		_c.SetTargetLocationID(*v)
	}
	return _c
}

// SetExpectedLocationGeneration sets the "expected_location_generation" field.
func (_c *StorageMigrationItemCreate) SetExpectedLocationGeneration(v int64) *StorageMigrationItemCreate {
	_c.mutation.SetExpectedLocationGeneration(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StorageMigrationItemCreate) SetStatus(v storagemigrationitem.Status) *StorageMigrationItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StorageMigrationItemCreate) SetNillableStatus(v *storagemigrationitem.Status) *StorageMigrationItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the StorageTask entity.
func (_c *StorageMigrationItemCreate) SetTask(v *StorageTask) *StorageMigrationItemCreate {
	return _c.SetTaskID(v.ID)
}

// SetBlob sets the "blob" edge to the Blob entity.
func (_c *StorageMigrationItemCreate) SetBlob(v *Blob) *StorageMigrationItemCreate {
	return _c.SetBlobID(v.ID)
}

// SetSourceLocation sets the "source_location" edge to the BlobLocation entity.
func (_c *StorageMigrationItemCreate) SetSourceLocation(v *BlobLocation) *StorageMigrationItemCreate {
	return _c.SetSourceLocationID(v.ID)
}

// SetTargetLocation sets the "target_location" edge to the BlobLocation entity.
func (_c *StorageMigrationItemCreate) SetTargetLocation(v *BlobLocation) *StorageMigrationItemCreate {
	return _c.SetTargetLocationID(v.ID)
}

// Mutation returns the StorageMigrationItemMutation object of the builder.
func (_c *StorageMigrationItemCreate) Mutation() *StorageMigrationItemMutation {
	return _c.mutation
}

// Save creates the StorageMigrationItem in the database.
func (_c *StorageMigrationItemCreate) Save(ctx context.Context) (*StorageMigrationItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageMigrationItemCreate) SaveX(ctx context.Context) *StorageMigrationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageMigrationItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageMigrationItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageMigrationItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := storagemigrationitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := storagemigrationitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := storagemigrationitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageMigrationItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StorageMigrationItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StorageMigrationItem.updated_at"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "StorageMigrationItem.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := storagemigrationitem.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationItem.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlobID(); !ok {
		return &ValidationError{Name: "blob_id", err: errors.New(`ent: missing required field "StorageMigrationItem.blob_id"`)}
	}
	if v, ok := _c.mutation.BlobID(); ok {
		if err := storagemigrationitem.BlobIDValidator(v); err != nil {
			return &ValidationError{Name: "blob_id", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationItem.blob_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceLocationID(); !ok {
		return &ValidationError{Name: "source_location_id", err: errors.New(`ent: missing required field "StorageMigrationItem.source_location_id"`)}
	}
	if v, ok := _c.mutation.SourceLocationID(); ok {
		if err := storagemigrationitem.SourceLocationIDValidator(v); err != nil {
			return &ValidationError{Name: "source_location_id", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationItem.source_location_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedLocationGeneration(); !ok {
		return &ValidationError{Name: "expected_location_generation", err: errors.New(`ent: missing required field "StorageMigrationItem.expected_location_generation"`)}
	}
	if v, ok := _c.mutation.ExpectedLocationGeneration(); ok {
		if err := storagemigrationitem.ExpectedLocationGenerationValidator(v); err != nil {
			return &ValidationError{Name: "expected_location_generation", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationItem.expected_location_generation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StorageMigrationItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := storagemigrationitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StorageMigrationItem.status": %w`, err)}
		}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "StorageMigrationItem.task"`)}
	}
	if len(_c.mutation.BlobIDs()) == 0 {
		return &ValidationError{Name: "blob", err: errors.New(`ent: missing required edge "StorageMigrationItem.blob"`)}
	}
	if len(_c.mutation.SourceLocationIDs()) == 0 {
		return &ValidationError{Name: "source_location", err: errors.New(`ent: missing required edge "StorageMigrationItem.source_location"`)}
	}
	return nil
}

func (_c *StorageMigrationItemCreate) sqlSave(ctx context.Context) (*StorageMigrationItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageMigrationItemCreate) createSpec() (*StorageMigrationItem, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageMigrationItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storagemigrationitem.Table, sqlgraph.NewFieldSpec(storagemigrationitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(storagemigrationitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(storagemigrationitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpectedLocationGeneration(); ok {
		_spec.SetField(storagemigrationitem.FieldExpectedLocationGeneration, field.TypeInt64, value)
		_node.ExpectedLocationGeneration = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(storagemigrationitem.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   storagemigrationitem.TaskTable,
			Columns: []string{storagemigrationitem.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storagetask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   storagemigrationitem.BlobTable,
			Columns: []string{storagemigrationitem.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlobID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   storagemigrationitem.SourceLocationTable,
			Columns: []string{storagemigrationitem.SourceLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bloblocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceLocationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   storagemigrationitem.TargetLocationTable,
			Columns: []string{storagemigrationitem.TargetLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bloblocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetLocationID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StorageMigrationItemCreateBulk is the builder for creating many StorageMigrationItem entities in bulk.
type StorageMigrationItemCreateBulk struct {
	config
	err      error
	builders []*StorageMigrationItemCreate
}

// Save creates the StorageMigrationItem entities in the database.
func (_c *StorageMigrationItemCreateBulk) Save(ctx context.Context) ([]*StorageMigrationItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageMigrationItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageMigrationItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageMigrationItemCreateBulk) SaveX(ctx context.Context) []*StorageMigrationItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageMigrationItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageMigrationItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
