// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/storagetask"
)

// StorageTaskCreate is the builder for creating a StorageTask entity.
type StorageTaskCreate struct {
	config
	mutation *StorageTaskMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *StorageTaskCreate) SetCreatedAt(v time.Time) *StorageTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableCreatedAt(v *time.Time) *StorageTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StorageTaskCreate) SetUpdatedAt(v time.Time) *StorageTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableUpdatedAt(v *time.Time) *StorageTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *StorageTaskCreate) SetOperationID(v string) *StorageTaskCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *StorageTaskCreate) SetIdempotencyKey(v string) *StorageTaskCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *StorageTaskCreate) SetRequestHash(v string) *StorageTaskCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *StorageTaskCreate) SetActorID(v int) *StorageTaskCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableActorID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *StorageTaskCreate) SetProjectID(v int) *StorageTaskCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableProjectID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *StorageTaskCreate) SetKind(v string) *StorageTaskCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StorageTaskCreate) SetStatus(v storagetask.Status) *StorageTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableStatus(v *storagetask.Status) *StorageTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *StorageTaskCreate) SetPhase(v string) *StorageTaskCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillablePhase(v *string) *StorageTaskCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetCleanupStatus sets the "cleanup_status" field.
func (_c *StorageTaskCreate) SetCleanupStatus(v storagetask.CleanupStatus) *StorageTaskCreate {
	_c.mutation.SetCleanupStatus(v)
	return _c
}

// SetNillableCleanupStatus sets the "cleanup_status" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableCleanupStatus(v *storagetask.CleanupStatus) *StorageTaskCreate {
	if v != nil {
		_c.SetCleanupStatus(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *StorageTaskCreate) SetErrorCode(v string) *StorageTaskCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableErrorCode(v *string) *StorageTaskCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *StorageTaskCreate) SetResourceID(v int) *StorageTaskCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableResourceID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetSourceRevisionID sets the "source_revision_id" field.
func (_c *StorageTaskCreate) SetSourceRevisionID(v int) *StorageTaskCreate {
	_c.mutation.SetSourceRevisionID(v)
	return _c
}

// SetNillableSourceRevisionID sets the "source_revision_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableSourceRevisionID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetSourceRevisionID(*v)
	}
	return _c
}

// SetTargetSpaceID sets the "target_space_id" field.
func (_c *StorageTaskCreate) SetTargetSpaceID(v int) *StorageTaskCreate {
	_c.mutation.SetTargetSpaceID(v)
	return _c
}

// SetNillableTargetSpaceID sets the "target_space_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableTargetSpaceID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetTargetSpaceID(*v)
	}
	return _c
}

// SetResultResourceID sets the "result_resource_id" field.
func (_c *StorageTaskCreate) SetResultResourceID(v int) *StorageTaskCreate {
	_c.mutation.SetResultResourceID(v)
	return _c
}

// SetNillableResultResourceID sets the "result_resource_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableResultResourceID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetResultResourceID(*v)
	}
	return _c
}

// SetResultRevisionID sets the "result_revision_id" field.
func (_c *StorageTaskCreate) SetResultRevisionID(v int) *StorageTaskCreate {
	_c.mutation.SetResultRevisionID(v)
	return _c
}

// SetNillableResultRevisionID sets the "result_revision_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableResultRevisionID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetResultRevisionID(*v)
	}
	return _c
}

// SetResultArtifactID sets the "result_artifact_id" field.
func (_c *StorageTaskCreate) SetResultArtifactID(v int) *StorageTaskCreate {
	_c.mutation.SetResultArtifactID(v)
	return _c
}

// SetNillableResultArtifactID sets the "result_artifact_id" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableResultArtifactID(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetResultArtifactID(*v)
	}
	return _c
}

// SetExpectedSourceGeneration sets the "expected_source_generation" field.
func (_c *StorageTaskCreate) SetExpectedSourceGeneration(v int64) *StorageTaskCreate {
	_c.mutation.SetExpectedSourceGeneration(v)
	return _c
}

// SetNillableExpectedSourceGeneration sets the "expected_source_generation" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableExpectedSourceGeneration(v *int64) *StorageTaskCreate {
	if v != nil {
		_c.SetExpectedSourceGeneration(*v)
	}
	return _c
}

// SetExpectedTranslationGeneration sets the "expected_translation_generation" field.
func (_c *StorageTaskCreate) SetExpectedTranslationGeneration(v int64) *StorageTaskCreate {
	_c.mutation.SetExpectedTranslationGeneration(v)
	return _c
}

// SetNillableExpectedTranslationGeneration sets the "expected_translation_generation" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableExpectedTranslationGeneration(v *int64) *StorageTaskCreate {
	if v != nil {
		_c.SetExpectedTranslationGeneration(*v)
	}
	return _c
}

// SetExpectedStorageGeneration sets the "expected_storage_generation" field.
func (_c *StorageTaskCreate) SetExpectedStorageGeneration(v int64) *StorageTaskCreate {
	_c.mutation.SetExpectedStorageGeneration(v)
	return _c
}

// SetNillableExpectedStorageGeneration sets the "expected_storage_generation" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableExpectedStorageGeneration(v *int64) *StorageTaskCreate {
	if v != nil {
		_c.SetExpectedStorageGeneration(*v)
	}
	return _c
}

// SetExpectedLocationGeneration sets the "expected_location_generation" field.
func (_c *StorageTaskCreate) SetExpectedLocationGeneration(v int64) *StorageTaskCreate {
	_c.mutation.SetExpectedLocationGeneration(v)
	return _c
}

// SetNillableExpectedLocationGeneration sets the "expected_location_generation" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableExpectedLocationGeneration(v *int64) *StorageTaskCreate {
	if v != nil {
		_c.SetExpectedLocationGeneration(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *StorageTaskCreate) SetAttempts(v int) *StorageTaskCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableAttempts(v *int) *StorageTaskCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetRetryStartedAt sets the "retry_started_at" field.
func (_c *StorageTaskCreate) SetRetryStartedAt(v time.Time) *StorageTaskCreate {
	_c.mutation.SetRetryStartedAt(v)
	return _c
}

// SetNillableRetryStartedAt sets the "retry_started_at" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableRetryStartedAt(v *time.Time) *StorageTaskCreate {
	if v != nil {
		_c.SetRetryStartedAt(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *StorageTaskCreate) SetNextRetryAt(v time.Time) *StorageTaskCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableNextRetryAt(v *time.Time) *StorageTaskCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// SetDeadline sets the "deadline" field.
func (_c *StorageTaskCreate) SetDeadline(v time.Time) *StorageTaskCreate {
	_c.mutation.SetDeadline(v)
	return _c
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (_c *StorageTaskCreate) SetNillableDeadline(v *time.Time) *StorageTaskCreate {
	if v != nil {
		_c.SetDeadline(*v)
	}
	return _c
}

// SetInput sets the "input" field.
func (_c *StorageTaskCreate) SetInput(v map[string]interface{}) *StorageTaskCreate {
	_c.mutation.SetInput(v)
	return _c
}

// Mutation returns the StorageTaskMutation object of the builder.
func (_c *StorageTaskCreate) Mutation() *StorageTaskMutation {
	return _c.mutation
}

// Save creates the StorageTask in the database.
func (_c *StorageTaskCreate) Save(ctx context.Context) (*StorageTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageTaskCreate) SaveX(ctx context.Context) *StorageTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := storagetask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := storagetask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		v := storagetask.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := storagetask.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := storagetask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := storagetask.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.CleanupStatus(); !ok {
		v := storagetask.DefaultCleanupStatus
		_c.mutation.SetCleanupStatus(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := storagetask.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.ExpectedSourceGeneration(); !ok {
		v := storagetask.DefaultExpectedSourceGeneration
		_c.mutation.SetExpectedSourceGeneration(v)
	}
	if _, ok := _c.mutation.ExpectedTranslationGeneration(); !ok {
		v := storagetask.DefaultExpectedTranslationGeneration
		_c.mutation.SetExpectedTranslationGeneration(v)
	}
	if _, ok := _c.mutation.ExpectedStorageGeneration(); !ok {
		v := storagetask.DefaultExpectedStorageGeneration
		_c.mutation.SetExpectedStorageGeneration(v)
	}
	if _, ok := _c.mutation.ExpectedLocationGeneration(); !ok {
		v := storagetask.DefaultExpectedLocationGeneration
		_c.mutation.SetExpectedLocationGeneration(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := storagetask.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StorageTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StorageTask.updated_at"`)}
	}
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "StorageTask.operation_id"`)}
	}
	if v, ok := _c.mutation.OperationID(); ok {
		if err := storagetask.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "StorageTask.operation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "StorageTask.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := storagetask.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "StorageTask.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "StorageTask.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := storagetask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "StorageTask.request_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "StorageTask.actor_id"`)}
	}
	if v, ok := _c.mutation.ActorID(); ok {
		if err := storagetask.ActorIDValidator(v); err != nil {
			return &ValidationError{Name: "actor_id", err: fmt.Errorf(`ent: validator failed for field "StorageTask.actor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "StorageTask.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := storagetask.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "StorageTask.project_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "StorageTask.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := storagetask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "StorageTask.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StorageTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := storagetask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StorageTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "StorageTask.phase"`)}
	}
	if _, ok := _c.mutation.CleanupStatus(); !ok {
		return &ValidationError{Name: "cleanup_status", err: errors.New(`ent: missing required field "StorageTask.cleanup_status"`)}
	}
	if v, ok := _c.mutation.CleanupStatus(); ok {
		if err := storagetask.CleanupStatusValidator(v); err != nil {
			return &ValidationError{Name: "cleanup_status", err: fmt.Errorf(`ent: validator failed for field "StorageTask.cleanup_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "StorageTask.error_code"`)}
	}
	if _, ok := _c.mutation.ExpectedSourceGeneration(); !ok {
		return &ValidationError{Name: "expected_source_generation", err: errors.New(`ent: missing required field "StorageTask.expected_source_generation"`)}
	}
	if _, ok := _c.mutation.ExpectedTranslationGeneration(); !ok {
		return &ValidationError{Name: "expected_translation_generation", err: errors.New(`ent: missing required field "StorageTask.expected_translation_generation"`)}
	}
	if _, ok := _c.mutation.ExpectedStorageGeneration(); !ok {
		return &ValidationError{Name: "expected_storage_generation", err: errors.New(`ent: missing required field "StorageTask.expected_storage_generation"`)}
	}
	if _, ok := _c.mutation.ExpectedLocationGeneration(); !ok {
		return &ValidationError{Name: "expected_location_generation", err: errors.New(`ent: missing required field "StorageTask.expected_location_generation"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "StorageTask.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := storagetask.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "StorageTask.attempts": %w`, err)}
		}
	}
	return nil
}

func (_c *StorageTaskCreate) sqlSave(ctx context.Context) (*StorageTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageTaskCreate) createSpec() (*StorageTask, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storagetask.Table, sqlgraph.NewFieldSpec(storagetask.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(storagetask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(storagetask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(storagetask.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(storagetask.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(storagetask.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(storagetask.FieldActorID, field.TypeInt, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(storagetask.FieldProjectID, field.TypeInt, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(storagetask.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(storagetask.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(storagetask.FieldPhase, field.TypeString, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.CleanupStatus(); ok {
		_spec.SetField(storagetask.FieldCleanupStatus, field.TypeEnum, value)
		_node.CleanupStatus = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(storagetask.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(storagetask.FieldResourceID, field.TypeInt, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.SourceRevisionID(); ok {
		_spec.SetField(storagetask.FieldSourceRevisionID, field.TypeInt, value)
		_node.SourceRevisionID = &value
	}
	if value, ok := _c.mutation.TargetSpaceID(); ok {
		_spec.SetField(storagetask.FieldTargetSpaceID, field.TypeInt, value)
		_node.TargetSpaceID = &value
	}
	if value, ok := _c.mutation.ResultResourceID(); ok {
		_spec.SetField(storagetask.FieldResultResourceID, field.TypeInt, value)
		_node.ResultResourceID = &value
	}
	if value, ok := _c.mutation.ResultRevisionID(); ok {
		_spec.SetField(storagetask.FieldResultRevisionID, field.TypeInt, value)
		_node.ResultRevisionID = &value
	}
	if value, ok := _c.mutation.ResultArtifactID(); ok {
		_spec.SetField(storagetask.FieldResultArtifactID, field.TypeInt, value)
		_node.ResultArtifactID = &value
	}
	if value, ok := _c.mutation.ExpectedSourceGeneration(); ok {
		_spec.SetField(storagetask.FieldExpectedSourceGeneration, field.TypeInt64, value)
		_node.ExpectedSourceGeneration = value
	}
	if value, ok := _c.mutation.ExpectedTranslationGeneration(); ok {
		_spec.SetField(storagetask.FieldExpectedTranslationGeneration, field.TypeInt64, value)
		_node.ExpectedTranslationGeneration = value
	}
	if value, ok := _c.mutation.ExpectedStorageGeneration(); ok {
		_spec.SetField(storagetask.FieldExpectedStorageGeneration, field.TypeInt64, value)
		_node.ExpectedStorageGeneration = value
	}
	if value, ok := _c.mutation.ExpectedLocationGeneration(); ok {
		_spec.SetField(storagetask.FieldExpectedLocationGeneration, field.TypeInt64, value)
		_node.ExpectedLocationGeneration = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(storagetask.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.RetryStartedAt(); ok {
		_spec.SetField(storagetask.FieldRetryStartedAt, field.TypeTime, value)
		_node.RetryStartedAt = &value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(storagetask.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	if value, ok := _c.mutation.Deadline(); ok {
		_spec.SetField(storagetask.FieldDeadline, field.TypeTime, value)
		_node.Deadline = &value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(storagetask.FieldInput, field.TypeJSON, value)
		_node.Input = value
	}
	return _node, _spec
}

// StorageTaskCreateBulk is the builder for creating many StorageTask entities in bulk.
type StorageTaskCreateBulk struct {
	config
	err      error
	builders []*StorageTaskCreate
}

// Save creates the StorageTask entities in the database.
func (_c *StorageTaskCreateBulk) Save(ctx context.Context) ([]*StorageTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageTaskCreateBulk) SaveX(ctx context.Context) []*StorageTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
