// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/user"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/userbackend"
)

// UserBackendUpdate is the builder for updating UserBackend entities.
type UserBackendUpdate struct {
	config
	hooks    []Hook
	mutation *UserBackendMutation
}

// Where appends a list predicates to the UserBackendUpdate builder.
func (_u *UserBackendUpdate) Where(ps ...predicate.UserBackend) *UserBackendUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBackendUpdate) SetUpdatedAt(v time.Time) *UserBackendUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UserBackendUpdate) SetName(v string) *UserBackendUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserBackendUpdate) SetNillableName(v *string) *UserBackendUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBackendType sets the "backend_type" field.
func (_u *UserBackendUpdate) SetBackendType(v userbackend.BackendType) *UserBackendUpdate {
	_u.mutation.SetBackendType(v)
	return _u
}

// SetNillableBackendType sets the "backend_type" field if the given value is not nil.
func (_u *UserBackendUpdate) SetNillableBackendType(v *userbackend.BackendType) *UserBackendUpdate {
	if v != nil {
		_u.SetBackendType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *UserBackendUpdate) SetPriority(v int) *UserBackendUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *UserBackendUpdate) SetNillablePriority(v *int) *UserBackendUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *UserBackendUpdate) AddPriority(v int) *UserBackendUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetOptions sets the "options" field.
func (_u *UserBackendUpdate) SetOptions(v map[string]interface{}) *UserBackendUpdate {
	_u.mutation.SetOptions(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserBackendUpdate) SetUserID(id int) *UserBackendUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBackendUpdate) SetUser(v *User) *UserBackendUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserBackendMutation object of the builder.
func (_u *UserBackendUpdate) Mutation() *UserBackendMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBackendUpdate) ClearUser() *UserBackendUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserBackendUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBackendUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserBackendUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBackendUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBackendUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbackend.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBackendUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userbackend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserBackend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackendType(); ok {
		if err := userbackend.BackendTypeValidator(v); err != nil {
			return &ValidationError{Name: "backend_type", err: fmt.Errorf(`ent: validator failed for field "UserBackend.backend_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBackend.user"`)
	}
	return nil
}

func (_u *UserBackendUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbackend.Table, userbackend.Columns, sqlgraph.NewFieldSpec(userbackend.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbackend.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userbackend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackendType(); ok {
		_spec.SetField(userbackend.FieldBackendType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(userbackend.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(userbackend.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(userbackend.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbackend.UserTable,
			Columns: []string{userbackend.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbackend.UserTable,
			Columns: []string{userbackend.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbackend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserBackendUpdateOne is the builder for updating a single UserBackend entity.
type UserBackendUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBackendMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBackendUpdateOne) SetUpdatedAt(v time.Time) *UserBackendUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UserBackendUpdateOne) SetName(v string) *UserBackendUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserBackendUpdateOne) SetNillableName(v *string) *UserBackendUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBackendType sets the "backend_type" field.
func (_u *UserBackendUpdateOne) SetBackendType(v userbackend.BackendType) *UserBackendUpdateOne {
	_u.mutation.SetBackendType(v)
	return _u
}

// SetNillableBackendType sets the "backend_type" field if the given value is not nil.
func (_u *UserBackendUpdateOne) SetNillableBackendType(v *userbackend.BackendType) *UserBackendUpdateOne {
	if v != nil {
		_u.SetBackendType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *UserBackendUpdateOne) SetPriority(v int) *UserBackendUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *UserBackendUpdateOne) SetNillablePriority(v *int) *UserBackendUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *UserBackendUpdateOne) AddPriority(v int) *UserBackendUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetOptions sets the "options" field.
func (_u *UserBackendUpdateOne) SetOptions(v map[string]interface{}) *UserBackendUpdateOne {
	_u.mutation.SetOptions(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserBackendUpdateOne) SetUserID(id int) *UserBackendUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBackendUpdateOne) SetUser(v *User) *UserBackendUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserBackendMutation object of the builder.
func (_u *UserBackendUpdateOne) Mutation() *UserBackendMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBackendUpdateOne) ClearUser() *UserBackendUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserBackendUpdate builder.
func (_u *UserBackendUpdateOne) Where(ps ...predicate.UserBackend) *UserBackendUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserBackendUpdateOne) Select(field string, fields ...string) *UserBackendUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserBackend entity.
func (_u *UserBackendUpdateOne) Save(ctx context.Context) (*UserBackend, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBackendUpdateOne) SaveX(ctx context.Context) *UserBackend {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserBackendUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBackendUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBackendUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbackend.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBackendUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userbackend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserBackend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackendType(); ok {
		if err := userbackend.BackendTypeValidator(v); err != nil {
			return &ValidationError{Name: "backend_type", err: fmt.Errorf(`ent: validator failed for field "UserBackend.backend_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBackend.user"`)
	}
	return nil
}

func (_u *UserBackendUpdateOne) sqlSave(ctx context.Context) (_node *UserBackend, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbackend.Table, userbackend.Columns, sqlgraph.NewFieldSpec(userbackend.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBackend.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbackend.FieldID)
		for _, f := range fields {
			if !userbackend.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbackend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbackend.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userbackend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackendType(); ok {
		_spec.SetField(userbackend.FieldBackendType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(userbackend.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(userbackend.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(userbackend.FieldOptions, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbackend.UserTable,
			Columns: []string{userbackend.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbackend.UserTable,
			Columns: []string{userbackend.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserBackend{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbackend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
