// Code generated by ent, DO NOT EDIT.

package storagespace

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the storagespace type in the database.
	Label = "storage_space"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// FieldMarkerNonce holds the string denoting the marker_nonce field in the database.
	FieldMarkerNonce = "marker_nonce"
	// FieldBucket holds the string denoting the bucket field in the database.
	FieldBucket = "bucket"
	// FieldPrefix holds the string denoting the prefix field in the database.
	FieldPrefix = "prefix"
	// FieldOwnerKind holds the string denoting the owner_kind field in the database.
	FieldOwnerKind = "owner_kind"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldManagementGeneration holds the string denoting the management_generation field in the database.
	FieldManagementGeneration = "management_generation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldVersioned holds the string denoting the versioned field in the database.
	FieldVersioned = "versioned"
	// FieldCapacityBytes holds the string denoting the capacity_bytes field in the database.
	FieldCapacityBytes = "capacity_bytes"
	// FieldReservedBytes holds the string denoting the reserved_bytes field in the database.
	FieldReservedBytes = "reserved_bytes"
	// FieldCandidateBytes holds the string denoting the candidate_bytes field in the database.
	FieldCandidateBytes = "candidate_bytes"
	// FieldLiveBytes holds the string denoting the live_bytes field in the database.
	FieldLiveBytes = "live_bytes"
	// FieldPendingDeleteBytes holds the string denoting the pending_delete_bytes field in the database.
	FieldPendingDeleteBytes = "pending_delete_bytes"
	// EdgeConnection holds the string denoting the connection edge name in mutations.
	EdgeConnection = "connection"
	// Table holds the table name of the storagespace in the database.
	Table = "storage_spaces"
	// ConnectionTable is the table that holds the connection relation/edge.
	ConnectionTable = "storage_spaces"
	// ConnectionInverseTable is the table name for the StorageConnection entity.
	// It exists in this package in order to avoid circular dependency with the "storageconnection" package.
	ConnectionInverseTable = "storage_connections"
	// ConnectionColumn is the table column denoting the connection relation/edge.
	ConnectionColumn = "connection_id"
)

// Columns holds all SQL columns for storagespace fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldConnectionID,
	FieldName,
	FieldIdentity,
	FieldMarkerNonce,
	FieldBucket,
	FieldPrefix,
	FieldOwnerKind,
	FieldOwnerID,
	FieldManagementGeneration,
	FieldStatus,
	FieldVerified,
	FieldVersioned,
	FieldCapacityBytes,
	FieldReservedBytes,
	FieldCandidateBytes,
	FieldLiveBytes,
	FieldPendingDeleteBytes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ConnectionIDValidator is a validator for the "connection_id" field. It is called by the builders before save.
	ConnectionIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IdentityValidator is a validator for the "identity" field. It is called by the builders before save.
	IdentityValidator func(string) error
	// MarkerNonceValidator is a validator for the "marker_nonce" field. It is called by the builders before save.
	MarkerNonceValidator func(string) error
	// DefaultBucket holds the default value on creation for the "bucket" field.
	DefaultBucket string
	// DefaultPrefix holds the default value on creation for the "prefix" field.
	DefaultPrefix string
	// DefaultOwnerID holds the default value on creation for the "owner_id" field.
	DefaultOwnerID int
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(int) error
	// DefaultManagementGeneration holds the default value on creation for the "management_generation" field.
	DefaultManagementGeneration int64
	// ManagementGenerationValidator is a validator for the "management_generation" field. It is called by the builders before save.
	ManagementGenerationValidator func(int64) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultVersioned holds the default value on creation for the "versioned" field.
	DefaultVersioned bool
	// CapacityBytesValidator is a validator for the "capacity_bytes" field. It is called by the builders before save.
	CapacityBytesValidator func(int64) error
	// DefaultReservedBytes holds the default value on creation for the "reserved_bytes" field.
	DefaultReservedBytes int64
	// ReservedBytesValidator is a validator for the "reserved_bytes" field. It is called by the builders before save.
	ReservedBytesValidator func(int64) error
	// DefaultCandidateBytes holds the default value on creation for the "candidate_bytes" field.
	DefaultCandidateBytes int64
	// CandidateBytesValidator is a validator for the "candidate_bytes" field. It is called by the builders before save.
	CandidateBytesValidator func(int64) error
	// DefaultLiveBytes holds the default value on creation for the "live_bytes" field.
	DefaultLiveBytes int64
	// LiveBytesValidator is a validator for the "live_bytes" field. It is called by the builders before save.
	LiveBytesValidator func(int64) error
	// DefaultPendingDeleteBytes holds the default value on creation for the "pending_delete_bytes" field.
	DefaultPendingDeleteBytes int64
	// PendingDeleteBytesValidator is a validator for the "pending_delete_bytes" field. It is called by the builders before save.
	PendingDeleteBytesValidator func(int64) error
)

// OwnerKind defines the type for the "owner_kind" enum field.
type OwnerKind string

// OwnerKindSite is the default value of the OwnerKind enum.
const DefaultOwnerKind = OwnerKindSite

// OwnerKind values.
const (
	OwnerKindSite OwnerKind = "site"
	OwnerKindUser OwnerKind = "user"
	OwnerKindOrg  OwnerKind = "org"
)

func (ok OwnerKind) String() string {
	return string(ok)
}

// OwnerKindValidator is a validator for the "owner_kind" field enum values. It is called by the builders before save.
func OwnerKindValidator(ok OwnerKind) error {
	switch ok {
	case OwnerKindSite, OwnerKindUser, OwnerKindOrg:
		return nil
	default:
		return fmt.Errorf("storagespace: invalid enum value for owner_kind field: %q", ok)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusReadOnly Status = "read_only"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusReadOnly, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("storagespace: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the StorageSpace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIdentity orders the results by the identity field.
func ByIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentity, opts...).ToFunc()
}

// ByMarkerNonce orders the results by the marker_nonce field.
func ByMarkerNonce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarkerNonce, opts...).ToFunc()
}

// ByBucket orders the results by the bucket field.
func ByBucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucket, opts...).ToFunc()
}

// ByPrefix orders the results by the prefix field.
func ByPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefix, opts...).ToFunc()
}

// ByOwnerKind orders the results by the owner_kind field.
func ByOwnerKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerKind, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByManagementGeneration orders the results by the management_generation field.
func ByManagementGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementGeneration, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByVersioned orders the results by the versioned field.
func ByVersioned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersioned, opts...).ToFunc()
}

// ByCapacityBytes orders the results by the capacity_bytes field.
func ByCapacityBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacityBytes, opts...).ToFunc()
}

// ByReservedBytes orders the results by the reserved_bytes field.
func ByReservedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedBytes, opts...).ToFunc()
}

// ByCandidateBytes orders the results by the candidate_bytes field.
func ByCandidateBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCandidateBytes, opts...).ToFunc()
}

// ByLiveBytes orders the results by the live_bytes field.
func ByLiveBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiveBytes, opts...).ToFunc()
}

// ByPendingDeleteBytes orders the results by the pending_delete_bytes field.
func ByPendingDeleteBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingDeleteBytes, opts...).ToFunc()
}

// ByConnectionField orders the results by connection field.
func ByConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionStep(), sql.OrderByField(field, opts...))
	}
}
func newConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConnectionTable, ConnectionColumn),
	)
}
