// Code generated by ent, DO NOT EDIT.

package tmentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tmentry type in the database.
	Label = "tm_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScopeKey holds the string denoting the scope_key field in the database.
	FieldScopeKey = "scope_key"
	// FieldSourceHash holds the string denoting the source_hash field in the database.
	FieldSourceHash = "source_hash"
	// FieldSourceText holds the string denoting the source_text field in the database.
	FieldSourceText = "source_text"
	// FieldTargetText holds the string denoting the target_text field in the database.
	FieldTargetText = "target_text"
	// FieldSourceLang holds the string denoting the source_lang field in the database.
	FieldSourceLang = "source_lang"
	// FieldTargetLang holds the string denoting the target_lang field in the database.
	FieldTargetLang = "target_lang"
	// FieldUsageCount holds the string denoting the usage_count field in the database.
	FieldUsageCount = "usage_count"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the tmentry in the database.
	Table = "tm_entries"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "tm_entries"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "tm_entries"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
)

// Columns holds all SQL columns for tmentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldScopeKey,
	FieldSourceHash,
	FieldSourceText,
	FieldTargetText,
	FieldSourceLang,
	FieldTargetLang,
	FieldUsageCount,
	FieldProjectID,
	FieldOrganizationID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ScopeKeyValidator is a validator for the "scope_key" field. It is called by the builders before save.
	ScopeKeyValidator func(string) error
	// SourceHashValidator is a validator for the "source_hash" field. It is called by the builders before save.
	SourceHashValidator func(string) error
	// SourceTextValidator is a validator for the "source_text" field. It is called by the builders before save.
	SourceTextValidator func(string) error
	// TargetTextValidator is a validator for the "target_text" field. It is called by the builders before save.
	TargetTextValidator func(string) error
	// SourceLangValidator is a validator for the "source_lang" field. It is called by the builders before save.
	SourceLangValidator func(string) error
	// TargetLangValidator is a validator for the "target_lang" field. It is called by the builders before save.
	TargetLangValidator func(string) error
	// DefaultUsageCount holds the default value on creation for the "usage_count" field.
	DefaultUsageCount int
	// UsageCountValidator is a validator for the "usage_count" field. It is called by the builders before save.
	UsageCountValidator func(int) error
	// ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	ProjectIDValidator func(int) error
	// OrganizationIDValidator is a validator for the "organization_id" field. It is called by the builders before save.
	OrganizationIDValidator func(int) error
)

// OrderOption defines the ordering options for the TMEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScopeKey orders the results by the scope_key field.
func ByScopeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeKey, opts...).ToFunc()
}

// BySourceHash orders the results by the source_hash field.
func BySourceHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceHash, opts...).ToFunc()
}

// BySourceText orders the results by the source_text field.
func BySourceText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceText, opts...).ToFunc()
}

// ByTargetText orders the results by the target_text field.
func ByTargetText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetText, opts...).ToFunc()
}

// BySourceLang orders the results by the source_lang field.
func BySourceLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceLang, opts...).ToFunc()
}

// ByTargetLang orders the results by the target_lang field.
func ByTargetLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetLang, opts...).ToFunc()
}

// ByUsageCount orders the results by the usage_count field.
func ByUsageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageCount, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
