OrgId:
  name: orgId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

UserId:
  name: userId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

ProjectId:
  name: projectId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

ResourceId:
  name: resourceId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

TranslationJobId:
  name: translationJobId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

BackendId:
  name: backendId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

EntryId:
  name: entryId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

TemplateId:
  name: templateId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

Stage:
  name: stage
  in: path
  required: true
  schema:
    type: string
    enum: [translate, bootstrap]
