OrgId:
  name: orgId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

UserId:
  name: userId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

ProjectId:
  name: projectId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

ResourceId:
  name: resourceId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

TranslationJobId:
  name: translationJobId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

BackendId:
  name: backendId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

EntryId:
  name: entryId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

PromptTemplateId:
  name: promptTemplateId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

TranslationProfileId:
  name: translationProfileId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1

ExecutionPlanTemplateId:
  name: executionPlanTemplateId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1
