// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MeowSalty/LinguaFlow/backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerOrgID applies equality check predicate on the "owner_org_id" field. It's identical to OwnerOrgIDEQ.
func OwnerOrgID(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerOrgID, v))
}

// ResourceScope applies equality check predicate on the "resource_scope" field. It's identical to ResourceScopeEQ.
func ResourceScope(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldResourceScope, v))
}

// SourceLang applies equality check predicate on the "source_lang" field. It's identical to SourceLangEQ.
func SourceLang(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSourceLang, v))
}

// TargetLang applies equality check predicate on the "target_lang" field. It's identical to TargetLangEQ.
func TargetLang(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTargetLang, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldName, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDIsNil applies the IsNil predicate on the "owner_user_id" field.
func OwnerUserIDIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldOwnerUserID))
}

// OwnerUserIDNotNil applies the NotNil predicate on the "owner_user_id" field.
func OwnerUserIDNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldOwnerUserID))
}

// OwnerOrgIDEQ applies the EQ predicate on the "owner_org_id" field.
func OwnerOrgIDEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerOrgID, v))
}

// OwnerOrgIDNEQ applies the NEQ predicate on the "owner_org_id" field.
func OwnerOrgIDNEQ(v int) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldOwnerOrgID, v))
}

// OwnerOrgIDIn applies the In predicate on the "owner_org_id" field.
func OwnerOrgIDIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldOwnerOrgID, vs...))
}

// OwnerOrgIDNotIn applies the NotIn predicate on the "owner_org_id" field.
func OwnerOrgIDNotIn(vs ...int) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldOwnerOrgID, vs...))
}

// OwnerOrgIDIsNil applies the IsNil predicate on the "owner_org_id" field.
func OwnerOrgIDIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldOwnerOrgID))
}

// OwnerOrgIDNotNil applies the NotNil predicate on the "owner_org_id" field.
func OwnerOrgIDNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldOwnerOrgID))
}

// ResourceScopeEQ applies the EQ predicate on the "resource_scope" field.
func ResourceScopeEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldResourceScope, v))
}

// ResourceScopeNEQ applies the NEQ predicate on the "resource_scope" field.
func ResourceScopeNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldResourceScope, v))
}

// ResourceScopeIn applies the In predicate on the "resource_scope" field.
func ResourceScopeIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldResourceScope, vs...))
}

// ResourceScopeNotIn applies the NotIn predicate on the "resource_scope" field.
func ResourceScopeNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldResourceScope, vs...))
}

// ResourceScopeGT applies the GT predicate on the "resource_scope" field.
func ResourceScopeGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldResourceScope, v))
}

// ResourceScopeGTE applies the GTE predicate on the "resource_scope" field.
func ResourceScopeGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldResourceScope, v))
}

// ResourceScopeLT applies the LT predicate on the "resource_scope" field.
func ResourceScopeLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldResourceScope, v))
}

// ResourceScopeLTE applies the LTE predicate on the "resource_scope" field.
func ResourceScopeLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldResourceScope, v))
}

// ResourceScopeContains applies the Contains predicate on the "resource_scope" field.
func ResourceScopeContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldResourceScope, v))
}

// ResourceScopeHasPrefix applies the HasPrefix predicate on the "resource_scope" field.
func ResourceScopeHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldResourceScope, v))
}

// ResourceScopeHasSuffix applies the HasSuffix predicate on the "resource_scope" field.
func ResourceScopeHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldResourceScope, v))
}

// ResourceScopeEqualFold applies the EqualFold predicate on the "resource_scope" field.
func ResourceScopeEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldResourceScope, v))
}

// ResourceScopeContainsFold applies the ContainsFold predicate on the "resource_scope" field.
func ResourceScopeContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldResourceScope, v))
}

// SourceLangEQ applies the EQ predicate on the "source_lang" field.
func SourceLangEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldSourceLang, v))
}

// SourceLangNEQ applies the NEQ predicate on the "source_lang" field.
func SourceLangNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldSourceLang, v))
}

// SourceLangIn applies the In predicate on the "source_lang" field.
func SourceLangIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldSourceLang, vs...))
}

// SourceLangNotIn applies the NotIn predicate on the "source_lang" field.
func SourceLangNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldSourceLang, vs...))
}

// SourceLangGT applies the GT predicate on the "source_lang" field.
func SourceLangGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldSourceLang, v))
}

// SourceLangGTE applies the GTE predicate on the "source_lang" field.
func SourceLangGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldSourceLang, v))
}

// SourceLangLT applies the LT predicate on the "source_lang" field.
func SourceLangLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldSourceLang, v))
}

// SourceLangLTE applies the LTE predicate on the "source_lang" field.
func SourceLangLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldSourceLang, v))
}

// SourceLangContains applies the Contains predicate on the "source_lang" field.
func SourceLangContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldSourceLang, v))
}

// SourceLangHasPrefix applies the HasPrefix predicate on the "source_lang" field.
func SourceLangHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldSourceLang, v))
}

// SourceLangHasSuffix applies the HasSuffix predicate on the "source_lang" field.
func SourceLangHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldSourceLang, v))
}

// SourceLangEqualFold applies the EqualFold predicate on the "source_lang" field.
func SourceLangEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldSourceLang, v))
}

// SourceLangContainsFold applies the ContainsFold predicate on the "source_lang" field.
func SourceLangContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldSourceLang, v))
}

// TargetLangEQ applies the EQ predicate on the "target_lang" field.
func TargetLangEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldTargetLang, v))
}

// TargetLangNEQ applies the NEQ predicate on the "target_lang" field.
func TargetLangNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldTargetLang, v))
}

// TargetLangIn applies the In predicate on the "target_lang" field.
func TargetLangIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldTargetLang, vs...))
}

// TargetLangNotIn applies the NotIn predicate on the "target_lang" field.
func TargetLangNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldTargetLang, vs...))
}

// TargetLangGT applies the GT predicate on the "target_lang" field.
func TargetLangGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldTargetLang, v))
}

// TargetLangGTE applies the GTE predicate on the "target_lang" field.
func TargetLangGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldTargetLang, v))
}

// TargetLangLT applies the LT predicate on the "target_lang" field.
func TargetLangLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldTargetLang, v))
}

// TargetLangLTE applies the LTE predicate on the "target_lang" field.
func TargetLangLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldTargetLang, v))
}

// TargetLangContains applies the Contains predicate on the "target_lang" field.
func TargetLangContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldTargetLang, v))
}

// TargetLangHasPrefix applies the HasPrefix predicate on the "target_lang" field.
func TargetLangHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldTargetLang, v))
}

// TargetLangHasSuffix applies the HasSuffix predicate on the "target_lang" field.
func TargetLangHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldTargetLang, v))
}

// TargetLangEqualFold applies the EqualFold predicate on the "target_lang" field.
func TargetLangEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldTargetLang, v))
}

// TargetLangContainsFold applies the ContainsFold predicate on the "target_lang" field.
func TargetLangContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldTargetLang, v))
}

// HasOwnerUser applies the HasEdge predicate on the "owner_user" edge.
func HasOwnerUser() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerUserTable, OwnerUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerUserWith applies the HasEdge predicate on the "owner_user" edge with a given conditions (other predicates).
func HasOwnerUserWith(preds ...predicate.User) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newOwnerUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnerOrg applies the HasEdge predicate on the "owner_org" edge.
func HasOwnerOrg() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerOrgTable, OwnerOrgColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerOrgWith applies the HasEdge predicate on the "owner_org" edge with a given conditions (other predicates).
func HasOwnerOrgWith(preds ...predicate.Organization) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newOwnerOrgStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProjectBackends applies the HasEdge predicate on the "project_backends" edge.
func HasProjectBackends() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProjectBackendsTable, ProjectBackendsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectBackendsWith applies the HasEdge predicate on the "project_backends" edge with a given conditions (other predicates).
func HasProjectBackendsWith(preds ...predicate.ProjectBackend) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newProjectBackendsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStageBackendOverrides applies the HasEdge predicate on the "stage_backend_overrides" edge.
func HasStageBackendOverrides() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StageBackendOverridesTable, StageBackendOverridesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageBackendOverridesWith applies the HasEdge predicate on the "stage_backend_overrides" edge with a given conditions (other predicates).
func HasStageBackendOverridesWith(preds ...predicate.StageBackendOverride) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newStageBackendOverridesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGlossaryEntries applies the HasEdge predicate on the "glossary_entries" edge.
func HasGlossaryEntries() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GlossaryEntriesTable, GlossaryEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGlossaryEntriesWith applies the HasEdge predicate on the "glossary_entries" edge with a given conditions (other predicates).
func HasGlossaryEntriesWith(preds ...predicate.GlossaryEntry) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newGlossaryEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTmEntries applies the HasEdge predicate on the "tm_entries" edge.
func HasTmEntries() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TmEntriesTable, TmEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTmEntriesWith applies the HasEdge predicate on the "tm_entries" edge with a given conditions (other predicates).
func HasTmEntriesWith(preds ...predicate.TMEntry) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newTmEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJobs applies the HasEdge predicate on the "jobs" edge.
func HasJobs() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobsWith applies the HasEdge predicate on the "jobs" edge with a given conditions (other predicates).
func HasJobsWith(preds ...predicate.Job) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Project) predicate.Project {
	return predicate.Project(sql.NotPredicates(p))
}
