// Code generated by ent, DO NOT EDIT.

package storageconnection

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storageconnection type in the database.
	Label = "storage_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDriver holds the string denoting the driver field in the database.
	FieldDriver = "driver"
	// FieldOwnerKind holds the string denoting the owner_kind field in the database.
	FieldOwnerKind = "owner_kind"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldBackendID holds the string denoting the backend_id field in the database.
	FieldBackendID = "backend_id"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldPathStyle holds the string denoting the path_style field in the database.
	FieldPathStyle = "path_style"
	// FieldAuthSource holds the string denoting the auth_source field in the database.
	FieldAuthSource = "auth_source"
	// FieldActiveAuthGeneration holds the string denoting the active_auth_generation field in the database.
	FieldActiveAuthGeneration = "active_auth_generation"
	// FieldManagementGeneration holds the string denoting the management_generation field in the database.
	FieldManagementGeneration = "management_generation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHealth holds the string denoting the health field in the database.
	FieldHealth = "health"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// Table holds the table name of the storageconnection in the database.
	Table = "storage_connections"
)

// Columns holds all SQL columns for storageconnection fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDriver,
	FieldOwnerKind,
	FieldOwnerID,
	FieldBackendID,
	FieldEndpoint,
	FieldRegion,
	FieldPathStyle,
	FieldAuthSource,
	FieldActiveAuthGeneration,
	FieldManagementGeneration,
	FieldStatus,
	FieldHealth,
	FieldCheckedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultOwnerID holds the default value on creation for the "owner_id" field.
	DefaultOwnerID int
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(int) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultPathStyle holds the default value on creation for the "path_style" field.
	DefaultPathStyle bool
	// DefaultActiveAuthGeneration holds the default value on creation for the "active_auth_generation" field.
	DefaultActiveAuthGeneration int64
	// ActiveAuthGenerationValidator is a validator for the "active_auth_generation" field. It is called by the builders before save.
	ActiveAuthGenerationValidator func(int64) error
	// DefaultManagementGeneration holds the default value on creation for the "management_generation" field.
	DefaultManagementGeneration int64
	// ManagementGenerationValidator is a validator for the "management_generation" field. It is called by the builders before save.
	ManagementGenerationValidator func(int64) error
	// DefaultHealth holds the default value on creation for the "health" field.
	DefaultHealth string
)

// Driver defines the type for the "driver" enum field.
type Driver string

// Driver values.
const (
	DriverLocal Driver = "local"
	DriverS3    Driver = "s3"
)

func (_driver Driver) String() string {
	return string(_driver)
}

// DriverValidator is a validator for the "driver" field enum values. It is called by the builders before save.
func DriverValidator(_driver Driver) error {
	switch _driver {
	case DriverLocal, DriverS3:
		return nil
	default:
		return fmt.Errorf("storageconnection: invalid enum value for driver field: %q", _driver)
	}
}

// OwnerKind defines the type for the "owner_kind" enum field.
type OwnerKind string

// OwnerKindSite is the default value of the OwnerKind enum.
const DefaultOwnerKind = OwnerKindSite

// OwnerKind values.
const (
	OwnerKindSite OwnerKind = "site"
	OwnerKindUser OwnerKind = "user"
	OwnerKindOrg  OwnerKind = "org"
)

func (ok OwnerKind) String() string {
	return string(ok)
}

// OwnerKindValidator is a validator for the "owner_kind" field enum values. It is called by the builders before save.
func OwnerKindValidator(ok OwnerKind) error {
	switch ok {
	case OwnerKindSite, OwnerKindUser, OwnerKindOrg:
		return nil
	default:
		return fmt.Errorf("storageconnection: invalid enum value for owner_kind field: %q", ok)
	}
}

// AuthSource defines the type for the "auth_source" enum field.
type AuthSource string

// AuthSourceDeployment is the default value of the AuthSource enum.
const DefaultAuthSource = AuthSourceDeployment

// AuthSource values.
const (
	AuthSourceDeployment AuthSource = "deployment"
	AuthSourceStored     AuthSource = "stored"
)

func (as AuthSource) String() string {
	return string(as)
}

// AuthSourceValidator is a validator for the "auth_source" field enum values. It is called by the builders before save.
func AuthSourceValidator(as AuthSource) error {
	switch as {
	case AuthSourceDeployment, AuthSourceStored:
		return nil
	default:
		return fmt.Errorf("storageconnection: invalid enum value for auth_source field: %q", as)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusEnabled is the default value of the Status enum.
const DefaultStatus = StatusEnabled

// Status values.
const (
	StatusEnabled  Status = "enabled"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusEnabled, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("storageconnection: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the StorageConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDriver orders the results by the driver field.
func ByDriver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriver, opts...).ToFunc()
}

// ByOwnerKind orders the results by the owner_kind field.
func ByOwnerKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerKind, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByBackendID orders the results by the backend_id field.
func ByBackendID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackendID, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByPathStyle orders the results by the path_style field.
func ByPathStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathStyle, opts...).ToFunc()
}

// ByAuthSource orders the results by the auth_source field.
func ByAuthSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthSource, opts...).ToFunc()
}

// ByActiveAuthGeneration orders the results by the active_auth_generation field.
func ByActiveAuthGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveAuthGeneration, opts...).ToFunc()
}

// ByManagementGeneration orders the results by the management_generation field.
func ByManagementGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementGeneration, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHealth orders the results by the health field.
func ByHealth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealth, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}
